{
  "name": "SemanticModel",
  "compatibilityLevel": 1400,
  "model": {
    "culture": "nb-NO",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/SQL2018\\TAB;Reporting",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "KS-SQL2018",
            "database": "Reporting"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "Windows",
          "kind": "SQL",
          "path": "ks-sql2018;Reporting",
          "Username": "laila.kleven@ks.no",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "Funksjon Kostra",
        "columns": [
          {
            "name": "Funksjonskode",
            "dataType": "string",
            "sourceColumn": "Funksjonskode"
          },
          {
            "name": "Funksjon",
            "dataType": "string",
            "sourceColumn": "Funksjon"
          },
          {
            "name": "FunksjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "FunksjonskodeNavn"
          },
          {
            "name": "Tjenesteområde",
            "dataType": "string",
            "sourceColumn": "Tjenesteområde"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/SQL2018\\TAB;Reporting\",",
                "    #\"dbo_Funksjon Kostra\" = Source{[Schema=\"dbo\",Item=\"Funksjon Kostra\"]}[Data]",
                "in",
                "    #\"dbo_Funksjon Kostra\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/SQL2018\\TAB;Reporting\",",
                  "    #\"dbo_Funksjon Kostra\" = Source{[Schema=\"dbo\",Item=\"Funksjon Kostra\"]}[Data]",
                  "in",
                  "    #\"dbo_Funksjon Kostra\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ]
      },
      {
        "name": "Artsgruppe Kostra",
        "columns": [
          {
            "name": "Artsgruppekode",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Artsgruppekode"
          },
          {
            "name": "ArtsgruppeNavn",
            "dataType": "string",
            "sourceColumn": "ArtsgruppeNavn"
          },
          {
            "name": "ArtsgruppekodeNavn",
            "dataType": "string",
            "sourceColumn": "ArtsgruppekodeNavn"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/SQL2018\\TAB;Reporting\",",
                "    #\"dbo_Artsgruppe Kostra\" = Source{[Schema=\"dbo\",Item=\"Artsgruppe Kostra\"]}[Data]",
                "in",
                "    #\"dbo_Artsgruppe Kostra\""
              ]
            }
          }
        ]
      },
      {
        "name": "Region",
        "columns": [
          {
            "name": "Regionnummer",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Regionnummer"
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/SQL2018\\TAB;Reporting\",",
                "    dbo_Region = Source{[Schema=\"dbo\",Item=\"Region\"]}[Data]",
                "in",
                "    dbo_Region"
              ]
            }
          }
        ]
      },
      {
        "name": "Variabel",
        "columns": [
          {
            "name": "Variabelgruppe",
            "dataType": "string",
            "sourceColumn": "Variabelgruppe"
          },
          {
            "name": "Variabel",
            "dataType": "string",
            "sourceColumn": "Variabel"
          },
          {
            "name": "Variabelnavn",
            "dataType": "string",
            "sourceColumn": "Variabelnavn"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/SQL2018\\TAB;Reporting\",",
                "    dbo_Variabel = Source{[Schema=\"dbo\",Item=\"Variabel\"]}[Data]",
                "in",
                "    dbo_Variabel"
              ]
            }
          }
        ]
      },
      {
        "name": "År",
        "columns": [
          {
            "name": "År",
            "dataType": "int64",
            "sourceColumn": "År"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/SQL2018\\TAB;Reporting\",",
                "    dbo_År = Source{[Schema=\"dbo\",Item=\"År\"]}[Data]",
                "in",
                "    dbo_År"
              ]
            }
          }
        ]
      },
      {
        "name": "Kommune",
        "columns": [
          {
            "name": "Kommunenummer",
            "dataType": "string",
            "sourceColumn": "Kommunenummer"
          },
          {
            "name": "Kommunenavn",
            "dataType": "string",
            "sourceColumn": "Kommunenavn"
          },
          {
            "name": "KommuneNummernavn",
            "dataType": "string",
            "sourceColumn": "KommuneNummernavn"
          },
          {
            "name": "ASSS Kommunegruppe",
            "dataType": "string",
            "sourceColumn": "ASSS Kommunegruppe"
          },
          {
            "name": "Regionnummer",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Regionnummer"
          },
          {
            "name": "Kostrakategori",
            "dataType": "string",
            "sourceColumn": "Kostrakategori"
          },
          {
            "name": "GyldigFraDato",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "GyldigFraDato"
          },
          {
            "name": "GyldigTilDato",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "GyldigTilDato"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/SQL2018\\TAB;Reporting\",",
                "    dbo_Kommune = Source{[Schema=\"dbo\",Item=\"Kommune\"]}[Data]",
                "in",
                "    dbo_Kommune"
              ]
            }
          }
        ]
      },
      {
        "name": "Alle Data",
        "columns": [
          {
            "name": "Tabell",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Tabell"
          },
          {
            "name": "Kommunenummer",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Kommunenummer"
          },
          {
            "name": "År",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "År"
          },
          {
            "name": "Funksjonskode",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Funksjonskode"
          },
          {
            "name": "Artsgruppekode",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Artsgruppekode"
          },
          {
            "name": "Variabel",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Variabel"
          },
          {
            "name": "Verdi",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Verdi"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/SQL2018\\TAB;Reporting\",",
                "    #\"dbo_Alle Data\" = Source{[Schema=\"dbo\",Item=\"Alle Data\"]}[Data]",
                "in",
                "    #\"dbo_Alle Data\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Distinct Count of Kommunenummer",
            "expression": "DISTINCTCOUNT([Kommunenummer])",
            "isHidden": true
          },
          {
            "name": "Distinct Count of Tabell",
            "expression": "DISTINCTCOUNT([Tabell])",
            "isHidden": true
          },
          {
            "name": "Distinct Count of År",
            "expression": "DISTINCTCOUNT([År])",
            "isHidden": true
          },
          {
            "name": "Distinct Count of Funksjonskode",
            "expression": "DISTINCTCOUNT([Funksjonskode])",
            "isHidden": true
          },
          {
            "name": "Distinct Count of Variabel",
            "expression": "DISTINCTCOUNT([Variabel])",
            "isHidden": true
          },
          {
            "name": "Sum dataverdi",
            "expression": "SUM('Alle Data'[Verdi])"
          },
          {
            "name": "Snitt",
            "expression": "DIVIDE('Alle Data'[Sum dataverdi],'Alle Data'[Count of Rows])",
            "isHidden": true
          },
          {
            "name": "Count of Rows",
            "expression": "CALCULATE(COUNT('Alle Data'[Verdi]),'Alle Data'[Verdi]<>BLANK()) + 0",
            "isHidden": true
          },
          {
            "name": "Sum Verdi",
            "expression": "SUM('Alle Data'[Verdi])",
            "isHidden": true
          }
        ]
      },
      {
        "name": "Nøkkeltall tjenester",
        "columns": [
          {
            "name": "Barnehager",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Barnehager"
          },
          {
            "name": "Barnevern",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Barnevern"
          },
          {
            "name": "Grunnskole",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Grunnskole"
          },
          {
            "name": "Kommunehelse",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Kommunehelse"
          },
          {
            "name": "Samferdsel",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Samferdsel"
          },
          {
            "name": "Eiendomsforvaltning",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Eiendomsforvaltning"
          },
          {
            "name": "SosialeTjenester",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SosialeTjenester"
          },
          {
            "name": "PleieOgOmsorg",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PleieOgOmsorg"
          },
          {
            "name": "Andre",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Andre"
          },
          {
            "name": "Byggesak",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Byggesak"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/SQL2018\\TAB;Reporting\",",
                "    #\"dbo_Nøkkeltall tjenester\" = Source{[Schema=\"dbo\",Item=\"Nøkkeltall tjenester\"]}[Data]",
                "in",
                "    #\"dbo_Nøkkeltall tjenester\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Kommunale veier i km per 10 000 innbyggere",
            "expression": [
              "",
              "Divide(CALCULATE(Sum('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Lengde kommunalvei (km)\"),",
              "(CALCULATE(SUM('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Innbyggere (antall)\"))/10000)"
            ],
            "formatString": "0.0",
            "displayFolder": "Samferdsel"
          },
          {
            "name": "Antall km tilrettelagt for syklende som kommunen har ansvaret for per 10 000 innbyggere",
            "expression": [
              "",
              "Divide(CALCULATE(Sum('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Lengde  tilrettelagt for syklende som kommunen har ansvaret for (km)\"),",
              "(CALCULATE(SUM('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Innbyggere (antall)\"))/10000)"
            ],
            "formatString": "0.0",
            "displayFolder": "Samferdsel"
          },
          {
            "name": "Brutto driftsutgifter eksklusiv avskrivninger samferdsel per km (kroner)",
            "expression": [
              " ",
              "",
              "var agd10 = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "FILTER(ALL('Artsgruppe Kostra'[Artsgruppekode]),'Artsgruppe Kostra'[Artsgruppekode] = \"AGD10\"),",
              "FILTER(ALL('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] = \"332\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Beløp (1000 kr)\")",
              " )   ",
              "",
              "var a590= CALCULATE(SUM('Alle Data'[Verdi]),  ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "FILTER(ALL('Artsgruppe Kostra'[Artsgruppekode]),'Artsgruppe Kostra'[Artsgruppekode] = \"A590\"),",
              "FILTER(ALL('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] = \"332\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Beløp (1000 kr)\")",
              " ) ",
              "",
              "var vei = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11814\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Lengde kommunalvei (km)\")",
              ")",
              "",
              "Return ((agd10-a590)*1000)/vei"
            ],
            "formatString": "#,0",
            "displayFolder": "Samferdsel"
          },
          {
            "name": "Kostnader til gatebelysning per lyspunkt, kommunale veier",
            "expression": [
              "",
              "var gate = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12183\"),",
              "FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Brutto driftsutgifter til gatebelysning langs kommunale veier og gater (1000 kr)\")",
              ")   ",
              "",
              "var lys = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11845\"),",
              "FILTER(ALL(Variabel[Variabelnavn]),Variabel[Variabelnavn] = \"Lyspunkt langs kommunale veier og gater (antall)\")   ",
              ")  ",
              "",
              "Return divide((gate*1000),lys)"
            ],
            "formatString": "#,0",
            "displayFolder": "Samferdsel"
          },
          {
            "name": "Netto driftsutgifter eiendomsforvaltning av kommunens samlede netto driftsutgifter (prosent)",
            "expression": [
              "",
              "",
              "var nettoeien = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]), 'Artsgruppe Kostra'[Artsgruppekode]=\"AGD2\"),",
              "/*filter(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] in {\"121\"; \"130\"; /*\"190\";*/ \"221\"; \"222\"; \"261\"; \"381\"; \"386\"});*/",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] = \"FGK6a\"),",
              "FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var nettoalle = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12364\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Netto driftsutgifter totalt Beløp (1000 kr)\")",
              ")",
              "",
              "return divide(nettoeien,nettoalle)*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Eiendomsforvaltning"
          },
          {
            "name": "Samlet areal på formålsbyggene i kvadratmeter per innbygger",
            "expression": [
              "",
              "",
              "var areal = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11906\"),",
              "FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Areal (m2) Areal totalt\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] = \"FGK6\")",
              "",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11805\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Personer (antall) I alt\")",
              ")",
              "",
              "return divide(areal,bef)"
            ],
            "formatString": "0.0",
            "displayFolder": "Eiendomsforvaltning"
          },
          {
            "name": "Netto driftsutgifter til sosialtjenesten (f242/f243/f273/f276/f281) per innbygger 18-66 år (kroner)",
            "expression": [
              "",
              "",
              "var ndrsos = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "filter(ALL('Artsgruppe Kostra'[Artsgruppekode]), 'Artsgruppe Kostra'[Artsgruppekode] = \"AGD2\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"242\", \"243\", \"273\", \"276\", \"281\"}),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var person = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell]=\"11805\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) 18-66 år\")",
              ")",
              "",
              "return divide((ndrsos*1000),person)"
            ],
            "formatString": "#,0",
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "Netto driftsutgifter til ytelse til livsopphold (f281) per innbygger 18-66 år (kroner)",
            "expression": [
              "",
              "",
              "var ndr281 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "filter(ALL('Artsgruppe Kostra'[Artsgruppekode]), 'Artsgruppe Kostra'[Artsgruppekode] = \"AGD2\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"281\"}),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var person = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell]=\"11805\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) 18-66 år\")",
              ")",
              "",
              "return divide((ndr281*1000),person)"
            ],
            "formatString": "#,0",
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "Netto driftsutgifter tilbud personer med rusproblemer (f243) per innbygger 18-66 år (kroner)",
            "expression": [
              "",
              "",
              "var ndr243 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "filter(ALL('Artsgruppe Kostra'[Artsgruppekode]), 'Artsgruppe Kostra'[Artsgruppekode] = \"AGD2\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"243\"}),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var person = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell]=\"11805\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) 18-66 år\")",
              ")",
              "",
              "return divide((ndr243*1000),person)"
            ],
            "formatString": "#,0",
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "Andel sosialhjelpsmottakere av innbyggere 18-66 år (prosent)",
            "expression": [
              "",
              "",
              "var sosmott = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12219\"),",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Sosialhjelpsmottakere (antall)\")",
              ")",
              "var bef= CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell]=\"11805\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) 18-66 år\")",
              ")",
              "",
              "return divide(sosmott,bef)*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "Andel sosialhjelpsmottakere 18-24 år av innbyggere 18-24 år (prosent)",
            "expression": [
              "",
              "Divide(CALCULATE(Sum('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Sosialhjelpsmottakere 18-24 år (antall)\"),",
              "(CALCULATE(SUM('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Personer (antall) 18-24 år\")))*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "Andel sosialhjelpsmottakere 25-66 år av innbyggere 25-66 år (prosent)",
            "expression": [
              "",
              "Divide(CALCULATE(Sum('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Sosialhjelpsmottakere 25-66 år (antall)\"),",
              "(CALCULATE(SUM('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Personer (antall) 25-66 år\")))*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "Antall mottakere av kvalifiseringsstønad (f276) per 1 000 innbyggere 18-66 år",
            "expression": [
              "",
              "Divide(CALCULATE(Sum('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Deltakere (antall)\"),",
              "(CALCULATE(SUM('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Personer (antall) 18-66 år\")/1000))"
            ],
            "formatString": "0.0",
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "Stønad (bidrag+lån) per sosialhjelpsmottaker (kroner)",
            "expression": [
              "",
              "",
              "var stonad = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12219\"), ",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Samlet stønadssum (bidrag + lån)  (kr)\") ",
              ") ",
              "var sosmott = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12219\"), ",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Sosialhjelpsmottakere (antall)\") ",
              ")  ",
              "return divide(stonad,sosmott)"
            ],
            "formatString": "#,0",
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "Andel med sosialhjelp som hovedinntekt/mottak i 6 mnd eller mer (alle mottakere/aldre) (prosent)",
            "expression": [
              "",
              "",
              "var langtid= CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell]=\"12213\"),",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Sosialhjelpsmottakere 6 måneder eller mer og sosialhjelp som hovedinntekt  (antall)\") ",
              ") ",
              "var sosmott = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12219\"), ",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Sosialhjelpsmottakere (antall)\") ",
              ")  ",
              "return divide(langtid,sosmott)*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "Netto driftsutgifter grunnskole (f202) per elev (kroner)",
            "expression": [
              "",
              "",
              "var ndr202 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "filter(ALL('Artsgruppe Kostra'[Artsgruppekode]), 'Artsgruppe Kostra'[Artsgruppekode] = \"AGD2\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] = \"202\"),",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var elev = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell]=\"11977\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Elever i kommunale grunnskoler, vektet (antall)\")",
              ")",
              "",
              "return divide((ndr202*1000),elev)"
            ],
            "formatString": "#,0",
            "displayFolder": "Grunnskole"
          },
          {
            "name": "Gruppestørrelse (antall)",
            "expression": [
              "",
              "Divide(CALCULATE(Sum('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Elevtimer (antall) Elever alle trinn\"),",
              "(CALCULATE(SUM('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Lærertimer minus morsmål og finsk (antall) Elever alle trinn\")))"
            ],
            "formatString": "0.0",
            "displayFolder": "Grunnskole"
          },
          {
            "name": "Elever i kommunale og private grunnskoler som får spesialundervisning (prosent)",
            "expression": [
              "",
              "Divide(CALCULATE(Sum('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Elever i kommunale og private grunnskoler som får spesialundervisning  (antall) Elever alle trinn\"),",
              "(CALCULATE(SUM('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Elever i kommunale og private grunnskoler (antall) Elever alle trinn\")))*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Grunnskole"
          },
          {
            "name": "Årstimer til spesialundervisning per elev med spesialundervisning (antall)",
            "expression": [
              "",
              "Divide(CALCULATE(Sum('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Årstimer til spesialundervisning, kommunale og private grunnskoler (antall)\"),",
              "(CALCULATE(SUM('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Elever i kommunale og private grunnskoler som får spesialundervisning  (antall) Elever alle trinn\")))"
            ],
            "formatString": "0.0",
            "displayFolder": "Grunnskole"
          },
          {
            "name": "Elever med direkte overgang fra vg1 til vg2 (prosent)",
            "expression": [
              "",
              "Divide(CALCULATE(Sum('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Elever som var registrert i videregående opplæring vg2 samme år som avsluttet vg1 (antall)\"),",
              "(CALCULATE(SUM('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Elever som avsluttet vg1 (antall)\")))*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Grunnskole"
          },
          {
            "name": "Netto driftsutgifter barnevernstjenester per innbygger 0-17 år (kroner)",
            "expression": [
              "",
              "",
              "var ndrbv = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "filter(ALL('Artsgruppe Kostra'[Artsgruppekode]), 'Artsgruppe Kostra'[Artsgruppekode] = \"AGD2\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"244\", \"251\", \"252\"}),",
              "filter(ALL('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "var barn= CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(ALL('Alle Data'[Tabell]),'Alle Data'[Tabell]=\"11805\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) 0-17 år\")",
              ")",
              "",
              "return DIVIDE((ndrbv*1000),barn)"
            ],
            "formatString": "#,0",
            "displayFolder": "Barnevern"
          },
          {
            "name": "Andel barn med undersøkelser i forhold til innbyggere 0-17 år (prosent)",
            "expression": [
              "",
              "DIVIDE(CALCULATE(sum('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Barn med undersøking  (antall)\"),",
              "(CALCULATE(sum('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Personer (antall) 0-17 år\")))*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Barnevern"
          },
          {
            "name": "Andel barn med barneverntiltak i forhold til innbyggere 0-17 år (prosent)",
            "expression": [
              "",
              "DIVIDE(CALCULATE(sum('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Barn med barnevernstiltak i løpet av året (antall) 0-22 år Tiltak i alt\"),",
              "(CALCULATE(sum('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Personer (antall) 0-17 år\")))*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Barnevern"
          },
          {
            "name": "Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)",
            "expression": [
              "",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Funksjon Kostra'[Funksjonskode]),'Funksjon Kostra'[Funksjonskode] = \"252\"),",
              "FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = ",
              "\"Barn med barnevernstiltak i løpet av året  (antall) 0-22 år\"))"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Barnevern"
          },
          {
            "name": "Andel barn som er plassert i løpet av året i prosent av antall barn 0-17 år",
            "expression": [
              "",
              "",
              "var barn017 = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(ALL('Alle Data'[Tabell]),'Alle Data'[Tabell]=\"11805\"),",
              "filter(all(Variabel[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer (antall) 0-17 år\")",
              ")",
              "",
              "return (DIVIDE('Nøkkeltall tjenester'",
              "[Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)],barn017))*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Barnevern"
          },
          {
            "name": "Barn med barnevernstiltak i løpet av året 0-22 år som ikke er plassert f251 (antall)",
            "expression": [
              "",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Funksjon Kostra'[Funksjonskode]),'Funksjon Kostra'[Funksjonskode] = \"251\"),",
              "FILTER(ALL(Variabel[Variabelnavn]), ",
              "Variabel[Variabelnavn] = \"Barn med barnevernstiltak i løpet av året  (antall) 0-22 år\"))"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Barnevern"
          },
          {
            "name": "Andel barn som ikke er plassert i løpet av året i prosent av alle i tiltak  (0-22 år)",
            "expression": [
              "",
              "",
              "var tiltak022 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all(Variabel[Variabelnavn]), ",
              "'Variabel'[Variabelnavn] = \"Barn med barnevernstiltak i løpet av året (antall) 0-22 år Tiltak i alt\")",
              ")",
              "",
              "return (DIVIDE('Nøkkeltall tjenester'",
              "[Barn med barnevernstiltak i løpet av året 0-22 år som ikke er plassert f251 (antall)],tiltak022))*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Barnevern"
          },
          {
            "name": "Brutto driftsutgifter per barn (f251) som ikke er plassert av barnevernet (kroner)",
            "expression": [
              "",
              "",
              "var brbv = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "FILTER(ALL('Artsgruppe Kostra'[Artsgruppekode]),'Artsgruppe Kostra'[Artsgruppekode] = \"AGD10\"),",
              "FILTER(ALL('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] = \"251\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              " )",
              "",
              "return DIVIDE((brbv*1000),'Nøkkeltall tjenester'[Barn med barnevernstiltak i løpet av året 0-22 år som ikke er plassert f251 (antall)])"
            ],
            "formatString": "#,0",
            "displayFolder": "Barnevern"
          },
          {
            "name": "Brutto driftsutgifter per barn (f252) som er plassert av barnevernet (kroner)",
            "expression": [
              "",
              "",
              "var brbv = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "FILTER(ALL('Artsgruppe Kostra'[Artsgruppekode]),'Artsgruppe Kostra'[Artsgruppekode] = \"AGD10\"),",
              "FILTER(ALL('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] = \"252\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              " )",
              "",
              "return divide((brbv*1000),'Nøkkeltall tjenester'[Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)])"
            ],
            "formatString": "#,0",
            "displayFolder": "Barnevern"
          },
          {
            "name": "Netto driftsutgifter kommunehelsetjenesten per innbygger (kroner)",
            "expression": [
              "",
              "",
              "var nettokom = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]), 'Artsgruppe Kostra'[Artsgruppekode]=\"AGD2\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"232\", \"233\", \"241\"}),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11805\"),",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) I alt\")",
              ")",
              "",
              "return divide((nettokom*1000),bef)"
            ],
            "formatString": "#,0",
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "Netto driftsutgifter kommunehelsetjenesten av kommunens samlede netto driftsutgifter (prosent)",
            "expression": [
              "",
              "",
              "var nettokom = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]), 'Artsgruppe Kostra'[Artsgruppekode]=\"AGD2\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"232\", \"233\", \"241\"}),",
              "FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var nettoalle = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12364\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Netto driftsutgifter totalt Beløp (1000 kr)\")",
              ")",
              "",
              "return divide(nettokom,nettoalle)*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "Årsverk helsestasjonen totalt per 10 000 innbyggere 0-20 år",
            "expression": [
              "",
              "",
              "var aarsverk = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11994\"),",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Avtalte årsverk (årsverk) Utdanning i alt\")",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11805\"), ",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) 0-20 år\")",
              ")",
              "",
              "return divide(aarsverk,(bef/10000))"
            ],
            "formatString": "0.0",
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "Årsverk helsesøstre totalt per 10 000 innbyggere 0-20 år",
            "expression": [
              "",
              "",
              "var aarsverk = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11994\"),",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Avtalte årsverk (årsverk) Helsesøster\")",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11805\"), ",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) 0-20 år\")",
              ")",
              "",
              "return divide(aarsverk,(bef/10000))"
            ],
            "formatString": "0.0",
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "Årsverk leger per 10 000 innbyggere (f120, f233, f241)",
            "expression": [
              "",
              "",
              "var aarsverk1 = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11996\"),",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Avtalte legeårsverk (årsverk) Avtaleform i alt\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"120\", \"233\", \"241\"})",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11805\"), ",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) I alt\") ",
              ")",
              "",
              "return divide(aarsverk1,(bef/10000))"
            ],
            "formatString": "0.0",
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "Brutto driftsutgifter (f232, f233 og f241) per innbygger (kroner)",
            "expression": [
              "",
              "",
              "var brkom = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "filter(ALL('Artsgruppe Kostra'[Artsgruppekode]), 'Artsgruppe Kostra'[Artsgruppekode] = \"AGD10\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"232\", \"233\", \"241\"}),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var person = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11805\"), ",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) I alt\") ",
              ")",
              "",
              "return divide((brkom*1000),person)"
            ],
            "formatString": "#,0",
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "Ledig liste-kapasitet",
            "expression": [
              "",
              "",
              "var kapasitet = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12005\"),",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Kapasitet hos fastlegene (iht. liste) (antall)\")",
              ")",
              "",
              "var pasienter = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12005\"),",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Antall pasienter på fastlegeliste (antall)\")",
              ")",
              "",
              "return divide(kapasitet,pasienter)*100"
            ],
            "formatString": "#,0",
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "Ledig liste-kapasitet i prosent av antall innbyggere",
            "expression": [
              "",
              "",
              "var kapasitet = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12005\"),",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Kapasitet hos fastlegene (iht. liste) (antall)\")",
              ")",
              "",
              "var pasienter = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12005\"),",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Antall pasienter på fastlegeliste (antall)\")",
              "",
              ")",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11805\"),",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) I alt\")",
              ")",
              "",
              "",
              "return divide((kapasitet-pasienter),bef)*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "Andel nyfødte med hjembesøk innen 2 uker etter hjemkomst (prosent)",
            "expression": [
              "",
              "",
              "var fodte = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11993\"),",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Barn (antall) Hjemmebesøk nyfødte\")",
              ")",
              "",
              "var barn= CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11820\"),",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Fødte i løpet av året (antall)\")",
              ")",
              "",
              "return divide(fodte,barn)*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "Gjennomsnittlig bistandsbehov hos mottakere av hjemmetjenester 0 til 66 år",
            "expression": [
              "",
              "",
              "var behov1 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Hjemmetjenestebrukere, noe/avgrenset bistandsbehov, 0-66 år (antall)\")",
              ")",
              "",
              "var behov2 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Hjemmetjenestebrukere, middels bistandsbehov, 0-66 år (antall)\")",
              ")",
              "",
              "var behov3 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Hjemmetjenestebrukere,  omfattende bistandsbehov,  0-66 år (antall)\")",
              ")",
              "",
              "return divide(((behov1*1)+(behov2*2)+(behov3*3)),(behov1+behov2+behov3))"
            ],
            "formatString": "0.0",
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "Gjennomsnittlig bistandsbehov hos mottakere av hjemmetjenester 67 år+",
            "expression": [
              "",
              "",
              "var behov1 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Hjemmetjenestebrukere, noe/avgrenset bistandsbehov, 67 år og over (antall)\")",
              ")",
              "",
              "var behov2 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Hjemmetjenestebrukere, middels bistandsbehov, 67 år og over (antall)\")",
              ")",
              "",
              "var behov3 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Hjemmetjenestebrukere, omfattende bistandsbehov, 67 år og over (antall)\")",
              ")",
              "",
              "return divide(((behov1*1)+(behov2*2)+(behov3*3)),(behov1+behov2+behov3))"
            ],
            "formatString": "0.0",
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "Andel brukere i institusjon som har omfattende bistandsbehov: Langtidsopphold (prosent)",
            "expression": [
              "",
              "Divide(CALCULATE(Sum('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Institusjon - beboere på langtidsopphold, omfattende bistandsbehov (antall)\"),",
              "(CALCULATE(SUM('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Institusjon - beboere på langtidsopphold (antall)\")))*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "Andel timer hjemmetjeneste brukere 0-66 år",
            "expression": [
              "",
              "",
              "var timer1 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell]=\"12292\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Gjennomsnittlig antall tildelte timer i uken, hjemmetjenestebrukere 0-66 år (antall)\")",
              ")",
              "var brukere1= CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell]=\"12003\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Brukere (antall) 0 - 66 år Heimeteneste\")",
              ")",
              "",
              "var timer2 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell]=\"12292\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Gjennomsnittlig antall tildelte timer i uken, hjemmetjenestebrukere 67 år og over (antall)\")",
              ")",
              "var brukere2= CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell]=\"12003\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn]  in {\"Brukere (antall) 67-79 år Heimeteneste\", \"Brukere (antall) over 80 år Heimeteneste\"})",
              ")",
              "",
              "return divide((timer1*brukere1*52),(timer1*brukere1*52+brukere2*timer2*52))*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "Andel timer hjemmetjeneste brukere 67 år +",
            "expression": [
              "",
              "",
              "var timer1 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell]=\"12292\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Gjennomsnittlig antall tildelte timer i uken, hjemmetjenestebrukere 0-66 år (antall)\")",
              ")",
              "var brukere1= CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell]=\"12003\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Brukere (antall) 0 - 66 år Heimeteneste\")",
              ")",
              "",
              "var timer2 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell]=\"12292\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Gjennomsnittlig antall tildelte timer i uken, hjemmetjenestebrukere 67 år og over (antall)\")",
              ")",
              "var brukere2= CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell]=\"12003\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn]  in {\"Brukere (antall) 67-79 år Heimeteneste\", \"Brukere (antall) over 80 år Heimeteneste\"})",
              ")",
              "",
              "return divide((timer2*brukere2*52),(timer1*brukere1*52+brukere2*timer2*52))*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "Netto driftsutgifter hjemmetjeneste 0-66 år per innbygger 0-66 år (kroner)",
            "expression": [
              "",
              "",
              "var netto066 = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "filter(all('Artsgruppe Kostra'), 'Artsgruppe Kostra'[Artsgruppekode] = \"AGD2\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"254\"})",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11805\"),",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) 0 - 66 år\")",
              ")",
              "",
              "return Divide((netto066*('Nøkkeltall tjenester'[Andel timer hjemmetjeneste brukere 0-66 år]/100)*1000),bef)"
            ],
            "formatString": "#,0",
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "Netto driftsutgifter hjemmetjeneste 67 + år per innbygger 67 år+ (kroner)",
            "expression": [
              "",
              "",
              "var netto066 = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "filter(all('Artsgruppe Kostra'), 'Artsgruppe Kostra'[Artsgruppekode] = \"AGD2\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"254\"})",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11805\"),",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) over 67 år\")",
              ")",
              "",
              "return divide((netto066*('Nøkkeltall tjenester'[Andel timer hjemmetjeneste brukere 67 år +]/100)*1000),bef)"
            ],
            "formatString": "#,0",
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "Andel innbyggere 0-66 år som er beboere på institusjon eller mottar hjemmetjenester (prosent)",
            "expression": [
              "",
              "",
              "var gr1 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Brukere (antall) 0 - 66 år Heimeteneste\")",
              ")",
              "",
              "var gr2= CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Brukere (antall) 0 - 66 år Institusjonstenester\")",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11805\"), ",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) 0 - 66 år\")",
              ")",
              "",
              "return divide((gr1+gr2),bef)*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "Andel innbyggere 80 år og eldre som mottar hjemmetjenester (prosent)",
            "expression": [
              "",
              "Divide(CALCULATE(Sum('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Brukere (antall) over 80 år Heimeteneste\"),",
              "(CALCULATE(SUM('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Personer (antall) over 80 år\")))*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "Andel innbyggere 80 år og eldre beboer på institusjon eller i bolig med heldøgns bemanning (prosent)",
            "expression": [
              "",
              "",
              "var gr1 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Beboere bolig m/ fast tilknyttet bemanning hele døgnet 80 år og over (antall)\")",
              ")",
              "",
              "var gr2= CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Institusjon - beboere 80 år og over (antall)\")",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11805\"), ",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) over 80 år\")",
              ")",
              "",
              "return divide((gr1+gr2),bef)*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "Andel brukere på institusjon 0-66 år (prosent)",
            "expression": [
              "",
              "Divide(CALCULATE(Sum('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Brukere (antall) 0 - 66 år Institusjonstenester\"),",
              "(CALCULATE(SUM('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Brukere (antall) I alt Institusjonstenester\")))*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "Brutto driftsutgifter per plass i institusjon (kroner)",
            "expression": [
              "",
              "",
              "var brutg = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "filter(ALL('Artsgruppe Kostra'[Artsgruppekode]), 'Artsgruppe Kostra'[Artsgruppekode] = \"AGD10\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"253\", \"261\"}),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var plasser = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11875\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Institusjon - alle disponible plasser (antall)\")",
              ")",
              "",
              "return divide((brutg*1000),plasser)"
            ],
            "formatString": "#,0",
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "Netto driftsutgifter hjemmetjeneste 0-66 år per mottaker 0-66 år (kroner)",
            "expression": [
              "",
              "",
              "var netto066 = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]), 'Artsgruppe Kostra'[Artsgruppekode]=\"AGD2\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"254\"}),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var mott066 = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12003\"),",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Brukere (antall) 0 - 66 år Heimeteneste\")",
              ")",
              "",
              "return divide((netto066*('Nøkkeltall tjenester'[Andel timer hjemmetjeneste brukere 0-66 år]/100)*1000),mott066)"
            ],
            "formatString": "#,0",
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "Netto driftsutgifter hjemmetjeneste 67 + år per mottaker 67 år+ (kroner)",
            "expression": [
              "",
              "",
              "var netto066 = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]), 'Artsgruppe Kostra'[Artsgruppekode]=\"AGD2\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"254\"}),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var mott67= CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell]=\"12003\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn]  in {\"Brukere (antall) 67-79 år Heimeteneste\", \"Brukere (antall) over 80 år Heimeteneste\"})",
              ")",
              "",
              "return divide((netto066*('Nøkkeltall tjenester'[Andel timer hjemmetjeneste brukere 67 år +]/100)*1000),mott67)"
            ],
            "formatString": "#,0",
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "Andel årsverk i brukerrettede tjenester med fagutdanning (prosent)",
            "expression": [
              "",
              "",
              "var gr1 = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12292\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] in {\"Årsverk i brukerrettede tjenester m/ helseutdanning fra videregående skole (antall)\", ",
              "\"Årsverk i brukerrettede tjenester m/ helseutdanning fra høyskole/universitet (antall)\"})",
              ")",
              "",
              "var gr2 = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11924\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Avtalte årsverk (årsverk) Omsorgstjenestene i alt\")",
              ")",
              "",
              "var gr3 = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11924\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] in {\"Avtalte årsverk (årsverk) Administrativt personell\", \"Avtalte årsverk (årsverk) Servicefunksjon\"})",
              ")",
              "",
              "return divide(gr1,(gr2-gr3))*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "Netto driftsutgifter barnehager per innbygger 1-5 år (kroner)",
            "expression": [
              "",
              "",
              "var nettobhg = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "filter(all('Artsgruppe Kostra'), 'Artsgruppe Kostra'[Artsgruppekode] = \"AGD2\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"201\", \"211\", \"221\"}),",
              "filter(ALL('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11805\"),",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) 1-5 år\")",
              ")",
              "",
              "return divide((nettobhg*1000),bef)"
            ],
            "formatString": "#,0",
            "displayFolder": "Barnehager"
          },
          {
            "name": "Netto driftsutgifter barnehager av kommunens samlede netto driftsutgifter (prosent)",
            "expression": [
              "",
              "",
              "var nettobhg = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]), 'Artsgruppe Kostra'[Artsgruppekode]=\"AGD2\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"201\", \"211\", \"221\"}),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var nettoalle = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12364\"),",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Netto driftsutgifter totalt Beløp (1000 kr)\")",
              ")",
              "",
              "return divide(nettobhg,nettoalle)*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Barnehager"
          },
          {
            "name": "Andel minoritetsspråklige barn i barnehage i forhold til innvandrerbarn (prosent)",
            "expression": [
              "",
              "Divide(CALCULATE(Sum('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Minoritetsspråklige barn (antall)\"),(",
              "CALCULATE(SUM('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Innvandrerbarn (antall)\")))*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Barnehager"
          },
          {
            "name": "Barn 1-2 år i barnehage av innbyggere 1-2 år (prosent)",
            "expression": [
              "",
              "",
              "var barnbhg12 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12056\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Barn i barnehage (antall) 1-2 år Alle eierforhold Alle oppholdskategorier\")",
              ")",
              "",
              "var barn12 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Personer (antall) 1-2 år\"),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell]=\"11805\")",
              ")",
              "",
              "return divide(barnbhg12,barn12)*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Barnehager"
          },
          {
            "name": "Barn 3-5 år i barnehage av innbyggere 3-5 år (prosent)",
            "expression": [
              "",
              "",
              "var barnbhg35 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12056\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Barn i barnehage (antall) 3-5 år Alle eierforhold Alle oppholdskategorier\")",
              ")",
              "",
              "var barn35 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Personer (antall) 3-5 år\"),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell]=\"11805\")",
              ")",
              "",
              "return divide(barnbhg35,barn35)*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Barnehager"
          },
          {
            "name": "Minoritetsspråklige barn i barnehage av alle barnehagebarn 1-5 år (prosent)",
            "expression": [
              "",
              "Divide(CALCULATE(Sum('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Minoritetsspråklige barn (antall)\"),(",
              "CALCULATE(SUM('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Barn i barnehage 1-5 år\")))*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Barnehager"
          },
          {
            "name": "Barn 1-5 år i barnehage av innbyggere 1-5 år (prosent)",
            "expression": [
              "",
              "divide(CALCULATE(sum('Alle Data'[Verdi]), 'Variabel'[Variabelnavn]=\"Barn i barnehage 1-5 år\"),",
              "(CALCULATE(sum('Alle Data'[Verdi]), Variabel[Variabelnavn]=\"Personer (antall) 1-5 år\")))*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Barnehager"
          },
          {
            "name": "Korrigerte brutto driftsutgifter f201 per korrigert oppholdstime i kommunale barnehage (kroner)",
            "expression": [
              "",
              "",
              "var kbr201 = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]), 'Artsgruppe Kostra'[Artsgruppekode] = \"AGD4\"),",
              "FILTER(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] = \"201\")",
              ")",
              "var kopph = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12216\"),",
              "filter(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Korrigerte oppholdstimer (timer) Kommune\")",
              ")",
              "return divide((kbr201*1000),kopph)"
            ],
            "formatString": "0",
            "displayFolder": "Barnehager"
          },
          {
            "name": "Andel menn av grunnbemanningen barnehager (prosent)",
            "expression": [
              "",
              "",
              "var ansatte = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12129\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] in {\"Ansatte (antall) Alle eierforhold Kvinne Annen grunnbemanning\", \"Ansatte (antall) Alle eierforhold Kvinne Pedagogisk leder\", \"Ansatte (antall) Alle eierforhold Kvinne Styrer\", \"Ansatte (antall) Alle eierforhold Mann Annen grunnbemanning\", \"Ansatte (antall) Alle eierforhold Mann Pedagogisk leder\", \"Ansatte (antall) Alle eierforhold Mann Styrer\"})",
              ")",
              "",
              "var menn = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12129\"),",
              "filter(ALL('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] in {\"Ansatte (antall) Alle eierforhold Mann Annen grunnbemanning\", \"Ansatte (antall) Alle eierforhold Mann Pedagogisk leder\", \"Ansatte (antall) Alle eierforhold Mann Styrer\"})",
              ")",
              "",
              "return divide(menn,ansatte)*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Barnehager"
          },
          {
            "name": "Barn i kommunale barnehager av alle barn i barnehage (prosent)",
            "expression": [
              "",
              "",
              "",
              "var barnkom = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12056\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Barn i barnehage (antall) 0-6 år Kommune Alle oppholdskategorier\")",
              ")",
              "",
              "var barnbhg = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Barn i barnehage (antall) 0-6 år Alle eierforhold Alle oppholdskategorier\"),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell]=\"12056\")",
              ")",
              "",
              "return divide(barnkom,barnbhg)*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Barnehager"
          },
          {
            "name": "Barn ekskl. minoritetsspråklige med ekstra ressurser av alle barn i kom. barnehager (prosent)*",
            "expression": [
              "",
              "",
              "var barnekstra = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12562\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Andel barn, eksklusive minoritetsspråklige, som får ekstra ressurser, i forhold til alle barn i kommunale barnehager (prosent)\")",
              ")",
              "",
              "return barnekstra"
            ],
            "formatString": "0.0",
            "displayFolder": "Barnehager"
          },
          {
            "name": "Barn i private barnehager av alle barn i barnehage (prosent)",
            "expression": [
              "",
              "",
              "var barnkom = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12056\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Barn i barnehage (antall) 0-6 år Privat Alle oppholdskategorier\")",
              ")",
              "",
              "var barnbhg = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Barn i barnehage (antall) 0-6 år Alle eierforhold Alle oppholdskategorier\"),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell]=\"12056\")",
              ")",
              "",
              "return divide(barnkom,barnbhg)*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Barnehager"
          },
          {
            "name": "Grunnbemanning per barn kommunale barnehager (prosent)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"BPA\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Barn per ansatt i barnehagen (bemanningstetthet) Kommunal\")",
              ")",
              "",
              "return divide(1,a)*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Barnehager"
          },
          {
            "name": "Grunnbemanning per barn private barnehager (prosent)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"BPA\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Barn per ansatt i barnehagen (bemanningstetthet) Privat\")",
              ")",
              "",
              "return divide(1,a)*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Barnehager"
          },
          {
            "name": "Antall barnehagelærere per barn kommunale barnehager",
            "expression": [
              "",
              "",
              "",
              "var bhg = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12436\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] in {\"Årsverk Kommune Barnehagelærer Grunnbemanning\", \"Årsverk Kommune Pedagogisk utdanning som tilsvarer utdanningskravet til styrer/pedagogisk leder Grunnbemanning\"})",
              ")",
              "",
              "/*var barnbhg = CALCULATE(sum('Alle Data'[Verdi]);*/",
              "/*filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\"12216\");*/",
              "/*filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Barn i barnehage korrigert for alder (antall) Kommune\")*/",
              "",
              "var barn1 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12056\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] in {\"Barn i barnehage (antall) 0 år Kommune Alle oppholdskategorier\", ",
              "\"Barn i barnehage (antall) 1-2 år Kommune Alle oppholdskategorier\"})",
              ")",
              "var barn2 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12056\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] in {\"Barn i barnehage (antall) 6 år Kommune Alle oppholdskategorier\", ",
              "\"Barn i barnehage (antall) 3-5 år Kommune Alle oppholdskategorier\"})",
              ")",
              "",
              "return divide(bhg,((barn1*2)+(barn2)))",
              "",
              "",
              "/*Barn er korrigert ut fra endret vekt - dette er ikke korrigert hos SSB*/",
              "/*27.3.2019 Laila */"
            ],
            "formatString": "0.00",
            "displayFolder": "Barnehager"
          },
          {
            "name": "Ansatte med barnehagelærerutdanning/annen pedagogisk utdanning av alle ansatte (prosent)",
            "expression": [
              "",
              "",
              "var utd = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"09345\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] in {\"Ansatte Pedagogisk utdanning som tilsvarer utdanningskravet til styrer/pedagogisk leder Kommune\", \"Ansatte Pedagogisk utdanning som tilsvarer utdanningskravet til styrer/pedagogisk leder Privat\",",
              "\"Ansatte Pedagogisk utdanning som tilsvarer utdanningskravet til styrer/pedagogisk leder Fylkeskommune/stat\", \"Ansatte Barnehagelærer Fylkeskommune/stat\", \"Ansatte Barnehagelærer Kommune\", \"Ansatte Barnehagelærer Privat\"})",
              ")",
              "",
              "var ansatte = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell]=\"12129\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] in {\"Ansatte (antall) Alle eierforhold Kvinne Alle stillingstyper\", \"Ansatte (antall) Alle eierforhold Mann Alle stillingstyper\"})",
              ")",
              "",
              "return divide(utd,ansatte)*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Barnehager"
          },
          {
            "name": "Nasjonale prøver 8. trinn, snitt andel nivå 3-5 (prosent)*",
            "expression": [
              "",
              "",
              "var les = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"NP8\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] in {\"Nasjonale prøver Trinn 8: Lesing Mestringsnivå 3\", \"Nasjonale prøver Trinn 8: Lesing Mestringsnivå 4\", \"Nasjonale prøver Trinn 8: Lesing Mestringsnivå 5\"})",
              ")",
              "var regn = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"NP8\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] in {\"Nasjonale prøver Trinn 8: Regning Mestringsnivå 3\", \"Nasjonale prøver Trinn 8: Regning Mestringsnivå 4\", \"Nasjonale prøver Trinn 8: Regning Mestringsnivå 5\" })",
              ")",
              "var eng = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"NP8\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] in {\"Nasjonale prøver Trinn 8: Engelsk Mestringsnivå 3\", \"Nasjonale prøver Trinn 8: Engelsk Mestringsnivå 4\", \"Nasjonale prøver Trinn 8: Engelsk Mestringsnivå 5\" })",
              ")",
              "",
              "return divide((eng + les + regn),3)"
            ],
            "formatString": "0.0",
            "displayFolder": "Grunnskole"
          },
          {
            "name": "Sykefravær barnehager (PAI) (prosent)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"ASSS\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Sykefravær Barnehage (PAI)\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "0.0",
            "displayFolder": "Barnehager"
          },
          {
            "name": "Brukertilfredshet barnehager (snitt skår)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"FUB\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Foreldreundersøkelsen: Tilfredshet\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "0.0",
            "displayFolder": "Barnehager"
          },
          {
            "name": "Sykefravær grunnskole (PAI) (prosent)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"ASSS\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Sykefravær Grunnskole (PAI)\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "0.0",
            "displayFolder": "Grunnskole"
          },
          {
            "name": "Eksamen snitt engelsk, regning og norsk*",
            "expression": [
              "",
              "",
              "var eng = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"ER\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Engelsk skriftlig eksamen\")",
              ")",
              "var regn = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"ER\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Matematikk skriftlig eksamen\")",
              ")",
              "var n1 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"ER\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Norsk hovedmål skriftlig eksamen\")",
              ")",
              "",
              "var n2 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"ER\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Norsk sidemål skriftlig eksamen\")",
              ")",
              "return (((n1+n2)/2)+eng+regn)/3"
            ],
            "formatString": "0.0",
            "displayFolder": "Grunnskole"
          },
          {
            "name": "Vurdering for læring (snitt skår)*",
            "expression": [
              "",
              "",
              "var a= CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"EU\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Elevundersøkelsen Trinn 10: Vurdering for læring\")",
              "",
              ")",
              "var b = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"EU\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Elevundersøkelsen Trinn 7: Vurdering for læring\")",
              ")",
              "",
              "return divide((a+b),2)"
            ],
            "formatString": "0.0",
            "displayFolder": "Grunnskole"
          },
          {
            "name": "Stønadslengde sosialhjelpsmottakere 18-24 år. Gjennomsnittlig antall måneder per år*",
            "expression": [
              "",
              "",
              "var lengde = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12219\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Gjennomsnittlig stønadstid 18-24 år (antall)\")",
              ")",
              "",
              "return lengde"
            ],
            "formatString": "0.0",
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "Etter KVP: Andel deltakere som gikk til arbeid/skole/utdanning (prosent)*",
            "expression": [
              "",
              "",
              "var kvp = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"STKVP\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Etter KVP: Andel deltakere som gikk arbeid/skole/utdanning\")",
              ")",
              "",
              "return kvp"
            ],
            "formatString": "0",
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "Sykefravær sosiale tjenester (PAI) (prosent)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"ASSS\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Sykefravær Sosiale tjenester (PAI)\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "0.0",
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "Brutto driftsutgifter per barn (f244) med undersøkelse eller tiltak (kroner)*",
            "expression": [
              "",
              "",
              "var br244 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12279\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Brutto driftsutgifter (funksjon 244) per barn med undersøking eller tiltak (kr)\")",
              ")",
              "",
              "return br244"
            ],
            "formatString": "#,0",
            "displayFolder": "Barnevern"
          },
          {
            "name": "Andel undersøkelser gjennomført i løpet av 3 måneder (prosent)*",
            "expression": [
              "",
              "",
              "var und= CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12280\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Undersøkingar med handsamingstid innan 3 månader (prosent)\")",
              ")",
              "",
              "return und"
            ],
            "formatString": "#,0",
            "displayFolder": "Barnevern"
          },
          {
            "name": "Sykefravær barnevern (PAI) (prosent)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"ASSS\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Sykefravær Barnevern (PAI)\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "0.0",
            "displayFolder": "Barnevern"
          },
          {
            "name": "Nasjonale prøver 9. trinn, snitt andel nivå 3-5 (prosent)*",
            "expression": [
              "",
              "",
              "var les = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"NP9\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] in {\"Nasjonale prøver Trinn 9: Lesing Mestringsnivå 3\", \"Nasjonale prøver Trinn 9: Lesing Mestringsnivå 4\", \"Nasjonale prøver Trinn 9: Lesing Mestringsnivå 5\"})",
              ")",
              "var regn = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"NP9\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] in {\"Nasjonale prøver Trinn 9: Regning Mestringsnivå 3\", \"Nasjonale prøver Trinn 9: Regning Mestringsnivå 4\", \"Nasjonale prøver Trinn 9: Regning Mestringsnivå 5\" })",
              ")",
              "",
              "return divide((les + regn),2)"
            ],
            "formatString": "0.0",
            "displayFolder": "Grunnskole"
          },
          {
            "name": "Sykefravær kommunehelse (PAI) (prosent)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"ASSS\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Sykefravær Kommunehelse (PAI)\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "0.0",
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "Nasjonale prøver 5. trinn, snitt andel nivå 2-3 (prosent)*",
            "expression": [
              "",
              "",
              "var les = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"NP5\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] in {\"Nasjonale prøver Trinn 5: Lesing Mestringsnivå 3\", \"Nasjonale prøver Trinn 5: Lesing Mestringsnivå 2\"})",
              ")",
              "var regn = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"NP5\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] in {\"Nasjonale prøver Trinn 5: Regning Mestringsnivå 3\", \"Nasjonale prøver Trinn 5: Regning Mestringsnivå 2\"})",
              ")",
              "",
              "var eng = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"NP5\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] in {\"Nasjonale prøver Trinn 5: Engelsk Mestringsnivå 3\", \"Nasjonale prøver Trinn 5: Engelsk Mestringsnivå 2\"})",
              ")",
              "",
              "return divide((les+regn+eng),3)"
            ],
            "formatString": "0.0",
            "displayFolder": "Grunnskole"
          },
          {
            "name": "Drenering/overvann, kroner per meter vei",
            "expression": [
              "",
              "",
              "var brutto = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"SFMT\"),",
              "FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Brutto driftsutg eks avskrivninger til drenering/overvann\")",
              ")   ",
              "",
              "var lengde = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11814\"),",
              "FILTER(ALL(Variabel[Variabelnavn]),Variabel[Variabelnavn] = \"Lengde kommunalvei (km)\")   ",
              ")  ",
              "",
              "Return divide( brutto,(lengde*1000))"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Samferdsel"
          },
          {
            "name": "Trafikksikkerhet inkludert skilting og veimerking, kroner per meter vei",
            "expression": [
              "",
              "",
              "var brutto = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"SFMT\"),",
              "FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Brutto driftsutg eks avskrivninger til trafikksikkerhet inkl skilting og vegmerking\")",
              ")   ",
              "",
              "var lengde = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11814\"),",
              "FILTER(ALL(Variabel[Variabelnavn]),Variabel[Variabelnavn] = \"Lengde kommunalvei (km)\")   ",
              ")  ",
              "",
              "Return divide( brutto,(lengde*1000))"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Samferdsel"
          },
          {
            "name": "Renhold, kroner per meter vei",
            "expression": [
              "",
              "",
              "var brutto = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"SFMT\"),",
              "FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Brutto driftsutg eks avskrivninger til renhold\")",
              ")   ",
              "",
              "var lengde = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11814\"),",
              "FILTER(ALL(Variabel[Variabelnavn]),Variabel[Variabelnavn] = \"Lengde kommunalvei (km)\")   ",
              ")  ",
              "",
              "Return divide( brutto,(lengde*1000))"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Samferdsel"
          },
          {
            "name": "Vinterdrift, kroner per meter vei",
            "expression": [
              "",
              "",
              "var brutto = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"SFMT\"),",
              "FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Brutto driftsutg eks avskrivninger til vinterdrift\")",
              ")   ",
              "",
              "var lengde = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11814\"),",
              "FILTER(ALL(Variabel[Variabelnavn]),Variabel[Variabelnavn] = \"Lengde kommunalvei (km)\")   ",
              ")  ",
              "",
              "Return divide( brutto,(lengde*1000))"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Samferdsel"
          },
          {
            "name": "Investeringer til veidekker (asfalt) per meter vei (kroner)",
            "expression": [
              "",
              "",
              "var brutto = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"SFMT\"),",
              "FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Investeringer til veidekker\")",
              ")   ",
              "",
              "var lengde = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11814\"),",
              "FILTER(ALL(Variabel[Variabelnavn]),Variabel[Variabelnavn] = \"Lengde kommunalvei (km)\")   ",
              ")  ",
              "",
              "Return divide( brutto,(lengde*1000))"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Samferdsel"
          },
          {
            "name": "Sykefravær samferdsel (PAI) (prosent)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"ASSS\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Sykefravær Samferdsel (PAI)\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "0.0",
            "displayFolder": "Samferdsel"
          },
          {
            "name": "Veidekker, kroner per meter vei",
            "expression": [
              "",
              "",
              "var brutto = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"SFMT\"),",
              "FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Brutto driftsutg eks avskrivninger til veidekker\")",
              ")   ",
              "",
              "var lengde = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11814\"),",
              "FILTER(ALL(Variabel[Variabelnavn]),Variabel[Variabelnavn] = \"Lengde kommunalvei (km)\")   ",
              ")  ",
              "",
              "Return divide( brutto,(lengde*1000))"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Samferdsel"
          },
          {
            "name": "Utgifter hele landet barnehage",
            "expression": [
              "",
              "",
              "var nettobhg =",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer]=\"12367\"),",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]), 'Artsgruppe Kostra'[Artsgruppekode]=\"AGD2\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"201\", \"211\", \"221\"}),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\"),",
              "FILTER(ALL(Kommune[Kommunenummer]), 'Kommune'[Kommunenummer]=\"EAK\")",
              "",
              ")",
              "var avsbhg = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer]=\"12367\"),",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]), 'Artsgruppe Kostra'[Artsgruppekode]=\"A590\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"201\", \"211\", \"221\"}),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\"),",
              "FILTER(ALL(Kommune[Kommunenummer]), 'Kommune'[Kommunenummer]=\"EAK\")",
              "",
              ")",
              "var innb = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer]=\"GHFK\"),",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] =\"Innbyggertall per 1. juli (Kilde: Grønt Hefte)\"),",
              "FILTER(ALL(Kommune[Kommunenummer]), 'Kommune'[Kommunenummer]=\"EAK\")",
              "",
              ")",
              "return divide((nettobhg-avsbhg),innb)*1000",
              "",
              "",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Økonomi"
          },
          {
            "name": "Beregnet UB barnehage",
            "expression": [
              "",
              "",
              "var I2_5aar = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] =\"Indeks innb. 2-5 år (Kilde: Grønt Hefte)\")",
              ")",
              "",
              "var Iukont = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] =\"Indeks barn 1 år utan kontant-støtte (Kilde: Grønt Hefte)\")",
              ")",
              "",
              "var IndHoyUtd  = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] =\"Indeks innb. m. høgare ut-danning (Kilde: Grønt Hefte)\")",
              ")",
              "",
              "var vekt2_5 = CALCULATE(SUM('Alle Data'[Verdi]),",
              "filter(all(Variabel[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Innb 2-5 år vektinger\"),",
              "filter(all(Kommune[Kommunenummer]), 'Kommune'[Kommunenummer]=\"EAK\"),",
              "filter(all('Funksjon Kostra'[Tjenesteområde]), 'Funksjon Kostra'[Tjenesteområde]=\"Barnehage\")",
              ")",
              "",
              "var vektukont = CALCULATE(SUM('Alle Data'[Verdi]),",
              "filter(all(Variabel[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Innb 1 år u/kont vektinger\"),",
              "filter(all(Kommune[Kommunenummer]), 'Kommune'[Kommunenummer]=\"EAK\"),",
              "filter(all('Funksjon Kostra'[Tjenesteområde]), 'Funksjon Kostra'[Tjenesteområde]=\"Barnehage\")",
              ")",
              "",
              "var vektHoyUtd = CALCULATE(SUM('Alle Data'[Verdi]),",
              "filter(all(Variabel[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Innbyggere med høyere utdanning vektinger\"),",
              "FILTER(ALL(Kommune[Kommunenummer]), 'Kommune'[Kommunenummer]=\"EAK\"),",
              "filter(all('Funksjon Kostra'[Tjenesteområde]), 'Funksjon Kostra'[Tjenesteområde]=\"Barnehage\")",
              ")",
              "",
              "",
              "return ((I2_5aar*vekt2_5)+(Iukont*vektukont)+(IndHoyUtd*vektHoyUtd))",
              "",
              "/* Må sjekke om alle filtrene trengs*/"
            ],
            "formatString": "#,0",
            "displayFolder": "Økonomi"
          },
          {
            "name": "Kommunens utgiftsbehov korrigert for forskjellene i inntektssystemet - barnehage",
            "expression": [
              "",
              "[Beregnet UB barnehage]*[Utgifter hele landet barnehage]"
            ],
            "displayFolder": "Økonomi"
          },
          {
            "name": "testvekt",
            "expression": [
              "",
              "",
              "var vektHoyUtd = CALCULATE(SUM('Alle Data'[Verdi]),",
              "filter(all(Variabel[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Innbyggere med høyere utdanning vektinger\"),",
              "/*filter(ALL(Kommune[KommuneNummernavn]); 'Kommune'[KommuneNummernavn]=\"Landet\")*/",
              "filter(all(Kommune[Kommunenummer]), 'Kommune'[Kommunenummer]=\"EAK\")",
              "/*filter(all('Funksjon Kostra'[Tjenesteområde]); 'Funksjon Kostra'[Tjenesteområde]=\"Barnehage\");*/",
              "/*filter(all('Alle Data'[Funksjonskode]); 'Alle Data'[Funksjonskode]=\"FGK7\");*/",
              "/*filter(all('Tabeller'[Tabellnummer]);'Tabeller'[Tabellnummer]=\"KMDV\")*/",
              "",
              ")",
              "",
              "",
              "",
              "return vektHoyUtd"
            ],
            "formatString": "0.00000000",
            "isHidden": true
          },
          {
            "name": "Lønnsutgifter eksklusiv sosiale utgifter barnehage",
            "expression": [
              "",
              "",
              "var lonn =",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer]=\"12367\"),",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]), 'Artsgruppe Kostra'[Artsgruppekode]=\"AG16\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"201\", \"211\", \"221\"}),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var pensjon=",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer]=\"12367\"),",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]), 'Artsgruppe Kostra'[Artsgruppekode]=\"A090\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"201\", \"211\", \"221\"}),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var arb =",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer]=\"12367\"),",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]), 'Artsgruppe Kostra'[Artsgruppekode]=\"A099\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"201\", \"211\", \"221\"}),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              "",
              "",
              ")",
              "return (lonn-pensjon-arb)",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Økonomi"
          },
          {
            "name": "Brutto driftsutgifter ekskludert avskrivninger barnehage",
            "expression": [
              "",
              "",
              "var bruttobhg =",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer]=\"12367\"),",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]), 'Artsgruppe Kostra'[Artsgruppekode]=\"AGD10\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"201\", \"211\", \"221\"}),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              "",
              ")",
              "var avsbhg = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer]=\"12367\"),",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]), 'Artsgruppe Kostra'[Artsgruppekode]=\"A590\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"201\", \"211\", \"221\"}),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              "",
              "",
              ")",
              "return (bruttobhg-avsbhg)",
              "",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Økonomi"
          },
          {
            "name": "Lønnsandel 1 barnehage",
            "expression": [
              "divide(",
              "[Lønnsutgifter eksklusiv sosiale utgifter barnehage]",
              ",",
              "[Brutto driftsutgifter ekskludert avskrivninger barnehage])",
              ""
            ],
            "formatString": "0.0000",
            "displayFolder": "Økonomi"
          },
          {
            "name": "Lønnsutgifter eksklusiv arbeidsgiveravgift barnehage",
            "expression": [
              "",
              "",
              "var lonn =",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer]=\"12367\"),",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]), 'Artsgruppe Kostra'[Artsgruppekode]=\"AG16\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"201\", \"211\", \"221\"}),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var arb =",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer]=\"12367\"),",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]), 'Artsgruppe Kostra'[Artsgruppekode]=\"A099\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"201\", \"211\", \"221\"}),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              "",
              "",
              ")",
              "return (lonn-arb)",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Økonomi"
          },
          {
            "name": "Lønnsandel 2 barnehage",
            "expression": [
              "divide(",
              "[Lønnsutgifter eksklusiv arbeidsgiveravgift barnehage]",
              ",",
              "[Brutto driftsutgifter ekskludert avskrivninger barnehage])"
            ],
            "formatString": "0.0000",
            "displayFolder": "Økonomi"
          },
          {
            "name": "Lønnsandel 1 barnehage hele landet",
            "expression": [
              "",
              "var lonn =",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer]=\"12367\"),",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]), 'Artsgruppe Kostra'[Artsgruppekode]=\"AG16\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"201\", \"211\", \"221\"}),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\"),",
              "filter(ALL('Kommune'[Kommunenummer]), 'Kommune'[Kommunenummer]=\"EAK\")",
              ")",
              "var pensjon=",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer]=\"12367\"),",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]), 'Artsgruppe Kostra'[Artsgruppekode]=\"A090\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"201\", \"211\", \"221\"}),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\"),",
              "filter(ALL('Kommune'[Kommunenummer]), 'Kommune'[Kommunenummer]=\"EAK\")",
              ")",
              "var arb =",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer]=\"12367\"),",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]), 'Artsgruppe Kostra'[Artsgruppekode]=\"A099\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"201\", \"211\", \"221\"}),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\"),",
              "filter(ALL('Kommune'[Kommunenummer]), 'Kommune'[Kommunenummer]=\"EAK\")",
              ")",
              "var bruttobhg =",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer]=\"12367\"),",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]), 'Artsgruppe Kostra'[Artsgruppekode]=\"AGD10\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"201\", \"211\", \"221\"}),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\"),",
              "filter(ALL('Kommune'[Kommunenummer]), 'Kommune'[Kommunenummer]=\"EAK\")",
              "",
              ")",
              "var avsbhg = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer]=\"12367\"),",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]), 'Artsgruppe Kostra'[Artsgruppekode]=\"A590\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"201\", \"211\", \"221\"}),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\"),",
              "filter(ALL('Kommune'[Kommunenummer]), 'Kommune'[Kommunenummer]=\"EAK\")",
              "",
              ")",
              "return ((lonn-pensjon-arb)/(bruttobhg-avsbhg))"
            ],
            "formatString": "0.0000",
            "displayFolder": "Økonomi"
          },
          {
            "name": "Lønnsutgiftsbehov pensjon barnehage",
            "expression": [
              "",
              "[Kommunens utgiftsbehov korrigert for forskjellene i inntektssystemet - barnehage]",
              "*",
              "[Lønnsandel 1 barnehage hele landet]"
            ],
            "formatString": "#,0",
            "displayFolder": "Økonomi"
          },
          {
            "name": "Andel pensjon kommune barnehage",
            "expression": [
              "",
              "",
              "var pensjon=",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer]=\"12367\"),",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]), 'Artsgruppe Kostra'[Artsgruppekode]=\"A090\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"201\", \"211\", \"221\"}),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "return divide(pensjon,[Lønnsutgifter eksklusiv sosiale utgifter barnehage])"
            ],
            "formatString": "#,0.0000",
            "displayFolder": "Økonomi"
          },
          {
            "name": "Andel arbeidsgiveravgift kommune barnehage",
            "expression": [
              "",
              "",
              "var arb =",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer]=\"12367\"),",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]), 'Artsgruppe Kostra'[Artsgruppekode]=\"A099\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"201\", \"211\", \"221\"}),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "return divide(arb,[Lønnsutgifter eksklusiv arbeidsgiveravgift barnehage])"
            ],
            "formatString": "#,0.0000",
            "displayFolder": "Økonomi"
          },
          {
            "name": "Innbyggere 1. juli",
            "expression": [
              "",
              "",
              "var innb = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"GHFK\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Innbyggertall per 1. juli (Kilde: Grønt Hefte)\")",
              ")",
              "",
              "return innb",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Økonomi"
          },
          {
            "name": "Elever i kommunale og private grunnskoler som får særskilt norsksopplæring (prosent)",
            "expression": [
              "",
              "",
              "var saer = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12234\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] ",
              "=\"Elever i kommunale og private grunnskoler som får særskilt norsksopplæring (antall)\")",
              ")",
              "var alleelev = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12234\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] ",
              "=\"Elever i kommunale og private grunnskoler (antall)\")",
              ")",
              "",
              "return DIVIDE(saer,alleelev)*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Grunnskole"
          },
          {
            "name": "Netto driftsutgifter skoleskyss (f223) per elev (kroner)",
            "expression": [
              "",
              "",
              "var ndr223 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "filter(ALL('Artsgruppe Kostra'[Artsgruppekode]), 'Artsgruppe Kostra'[Artsgruppekode] = \"AGD2\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] = \"223\"),",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var elev = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell]=\"11977\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Elever i kommunale grunnskoler, vektet (antall)\")",
              ")",
              "",
              "return divide((ndr223*1000),elev)"
            ],
            "formatString": "#,0",
            "displayFolder": "Grunnskole"
          },
          {
            "name": "Lærere i grunnskolen 40 år og yngre (prosent)",
            "expression": [
              "",
              "",
              "var l40 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12282\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] ",
              "= \"Lærere (antall) Begge kjønn 40 år og yngre\")",
              ")",
              "",
              "var alle = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12282\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] ",
              "= \"Lærere (antall) Begge kjønn Alle aldersgrupper\")",
              ")",
              "",
              "return ((divide(l40,alle))*100)",
              ""
            ],
            "formatString": "0.0",
            "displayFolder": "Grunnskole"
          },
          {
            "name": "Lærere i grunnskolen 40 - 49 år (prosent)",
            "expression": [
              "",
              "",
              "var l4049 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12282\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] ",
              "= \"Lærere (antall) Begge kjønn 41 til 49 år\")",
              ")",
              "",
              "var alle = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12282\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] ",
              "= \"Lærere (antall) Begge kjønn Alle aldersgrupper\")",
              ")",
              "",
              "return ((divide(l4049,alle))*100)"
            ],
            "formatString": "0.0",
            "displayFolder": "Grunnskole"
          },
          {
            "name": "Lærere i grunnskolen 50 - 59 år (prosent)",
            "expression": [
              "",
              "",
              "var l5059 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12282\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] ",
              "= \"Lærere (antall) Begge kjønn 50 til 59 år\")",
              ")",
              "",
              "var alle = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12282\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] ",
              "= \"Lærere (antall) Begge kjønn Alle aldersgrupper\")",
              ")",
              "",
              "return ((divide(l5059,alle))*100)"
            ],
            "formatString": "0.0",
            "displayFolder": "Grunnskole"
          },
          {
            "name": "Lærere i grunnskolen 60 år og eldre (prosent)",
            "expression": [
              "",
              "",
              "var l60 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12282\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] ",
              "= \"Lærere (antall) Begge kjønn 60 år og eldre\")",
              ")",
              "",
              "var alle = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12282\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] ",
              "= \"Lærere (antall) Begge kjønn Alle aldersgrupper\")",
              ")",
              "",
              "return ((divide(l60,alle))*100)"
            ],
            "formatString": "0.0",
            "displayFolder": "Grunnskole"
          },
          {
            "name": "Gjennomsnittlig antall elever per kommunale skole",
            "expression": [
              "",
              "",
              "var elever = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11971\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] ",
              "= \"Elever i kommunale skoler (antall)\")",
              ")",
              "",
              "var skoler = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11971\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] ",
              "= \"Kommunale grunnskoler (antall)\")",
              ")",
              "",
              "return (divide(elever,skoler))"
            ],
            "formatString": "#,0",
            "displayFolder": "Grunnskole"
          },
          {
            "name": "Elever i kommunale og private grunnskoler med spesialundervisning, 1.-4. trinn (prosent)",
            "expression": [
              "",
              "",
              "var spes = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12222\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] ",
              "= \"Elever i kommunale og private grunnskoler som får spesialundervisning  (antall) 1.-4. trinn\")",
              ")",
              "",
              "var elev = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12222\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] ",
              "= \"Elever i kommunale og private grunnskoler (antall) 1.-4. trinn\")",
              ")",
              "",
              "return ((divide(spes,elev))*100)"
            ],
            "formatString": "0.0",
            "displayFolder": "Grunnskole"
          },
          {
            "name": "Elever i kommunale og private grunnskoler med spesialundervisning, 5.-7. trinn (prosent)",
            "expression": [
              "",
              "",
              "var spes = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12222\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] ",
              "= \"Elever i kommunale og private grunnskoler som får spesialundervisning  (antall) 5.-7. trinn\")",
              ")",
              "",
              "var elev = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12222\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] ",
              "= \"Elever i kommunale og private grunnskoler (antall) 5.-7. trinn\")",
              ")",
              "",
              "return ((divide(spes,elev))*100)"
            ],
            "formatString": "0.0",
            "displayFolder": "Grunnskole"
          },
          {
            "name": "Elever i kommunale og private grunnskoler med spesialundervisning, 8.-10. trinn (prosent)",
            "expression": [
              "",
              "",
              "var spes = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12222\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] ",
              "= \"Elever i kommunale og private grunnskoler som får spesialundervisning  (antall) 8.-10. trinn\")",
              ")",
              "",
              "var elev = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12222\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] ",
              "= \"Elever i kommunale og private grunnskoler (antall) 8.-10. trinn\")",
              ")",
              "",
              "return ((divide(spes,elev))*100)"
            ],
            "formatString": "0.0",
            "displayFolder": "Grunnskole"
          },
          {
            "name": "Superformel1",
            "expression": [
              "",
              "",
              "var under_100 =",
              "/*",
              "     Summarize grupperer alle rader i en tabell etter hva man spesifiserer, i dette tilfellet Kommune og År",
              "     Spesifiserer et ekstra felt som er enten True eller False avhengig av om summen er < 100",
              "*/",
              "SUMMARIZE(",
              "     /*",
              "          Lager en tabell av rader i Alle Data som har:",
              "              Variabelkode: KSatr2009779556",
              "              Funksjonskode: 201, 211 eller 221",
              "              Artsgruppekode: 02",
              "              Verdi: Er et tall og ikke blankt",
              "     */",
              "     CALCULATETABLE  (",
              "         /*Tabellen man henter data fra*/",
              "         'Alle Data',",
              "         /*Filtere*/",
              "         Variabel[Variabelnavn] = \"Beløp (1000 kr)\",",
              "         'Alle Data'[Artsgruppekode] = \"AG16\",",
              "         'Alle Data'[Funksjonskode] IN {\"201\", \"211\", \"221\"},",
              "         IFERROR(VALUE(Kommune[Kommunenummer]),\"\"),",
              "         ISNUMBER('Alle Data'[Verdi])",
              "     ),",
              "     [Kommunenummer],",
              "     [År],",
              "     \"Mindre enn 100\",",
              "     SUM('Alle Data'[Verdi]) < 100",
              ")",
              "",
              "/**",
              "    EAK tabell = summarize innbtall_uten_eak med filter under 100",
              "*/",
              "",
              "var innbtall_uten_eak = ",
              "CALCULATETABLE('Alle Data',",
              "    FILTER(ALL('Alle Data'[Variabel]), [Variabel] = \"GRF1003982422\"),",
              "    FILTER(ALL('Alle Data'[Kommunenummer]), [Kommunenummer] <> \"EAK\")",
              "/*FILTER(ALL(Kommune[Kommunenummer]);Kommune[Kommunenummer] = IFERROR(VALUE(Kommune[Kommunenummer]);\"\"))*/",
              ")",
              "",
              "var eak_tabell =",
              "SUMMARIZE(",
              "    innbtall_uten_eak,",
              "    [År],",
              "    \"Kommunenummer\",",
              "    \"EAK\",",
              "    \"Verdi\",",
              "    SUM('Alle Data'[Verdi]) - ",
              "    CALCULATE(Sum ('Alle Data'[Verdi]),",
              "          /*Filtere*/",
              "          FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Innbyggertall per 1. juli\"),",
              "          /*Filtrer elementer i temp tabellen som har verdien True i Mindre enn 100*/",
              "          FILTER (",
              "                'Alle Data',",
              "               /*Hvis kombinasjonen kommunenummer + år eksisterer i temp og \"Mindre enn 100\" er True så tas den ikke med*/",
              "               CONTAINS (",
              "                     under_100, ",
              "                     /*Kolonne; Verdi*/",
              "                     [Kommunenummer], 'Alle Data'[Kommunenummer],",
              "                     [År], 'Alle Data'[År],",
              "                     [Mindre enn 100], TRUE",
              "               )",
              "          )",
              "     )",
              ")",
              "",
              "return SUMX(eak_tabell, [Verdi])",
              ""
            ],
            "isHidden": true,
            "displayFolder": "Økonomi"
          },
          {
            "name": "Andel sosialhjelpsmottakere som forsørger barn under 18 år (prosent)",
            "expression": [
              "",
              "",
              "var langtid= CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell]=\"12219\"),",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Sosialhjelpsmottakere som forsørger barn under 18 år (antall)\") ",
              ") ",
              "var sosmott = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12219\"), ",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Sosialhjelpsmottakere (antall)\") ",
              ")  ",
              "return divide(langtid,sosmott)*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "Årsverk ergoterapeuter per 10 000 innbyggere",
            "expression": [
              "",
              "",
              "var aarsverk = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"ÅRER\"),",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Årsverk ergoteraputer i alt\")",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11805\"), ",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) I alt\")",
              ")",
              "",
              "return divide(aarsverk,(bef/10000))"
            ],
            "formatString": "0.0",
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "Årsverk helsestasjonen totalt per 1 000 innbyggere 0-5 år",
            "expression": [
              "",
              "",
              "var aarsverk = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"ÅRHOS\"),",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Årsverk 0-5 totalt uten ledelse. Helsestasjon 0-5 år\")",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11805\"), ",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) 0-5 år\")",
              ")",
              "",
              "return divide(aarsverk,(bef/1000))"
            ],
            "formatString": "0.0",
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "Årsverk skolehelsetjenesten totalt per 1 000 innbyggere 6-20 år",
            "expression": [
              "",
              "",
              "var aarsverk = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"ÅRHOS\"),",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Årsverk totalt skolehelsetjenesten uten ledelse\")",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11805\"), ",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) 6-20 år\")",
              ")",
              "",
              "return DIVIDE(aarsverk,(bef/1000))"
            ],
            "formatString": "0.0",
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "Netto driftsutgifter forebygging, helsestasjons- og skolehelsetjeneste per innb. 0-20 år (kroner)",
            "expression": [
              "",
              "",
              "var nettokom = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]), 'Artsgruppe Kostra'[Artsgruppekode]=\"AGD2\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] =\"232\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11805\"),",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) 0-20 år\")",
              ")",
              "",
              "return divide((nettokom*1000),bef)"
            ],
            "formatString": "#,0",
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "Årsverk helsesykepleiere per 1 000 innbygger 0-5 år",
            "expression": [
              "",
              "",
              "var aarsverk = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"ÅRHOS\"),",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Årsverk helsesykepleiere uten ledelse. Helsestasjon 0-5 år\")",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11805\"), ",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) 0-5 år\")",
              ")",
              "",
              "return DIVIDE(aarsverk,(bef/1000))"
            ],
            "formatString": "0.0",
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "Årsverk totalt på helsestasjon per innbygger 0-5 år",
            "expression": [
              "",
              "",
              "var aarsverk = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"ÅRHOS\"),",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Årsverk 0-5 totalt uten ledelse. Helsestasjon 0-5 år\")",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11805\"), ",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) 0-5 år\")",
              ")",
              "",
              "return DIVIDE(aarsverk,bef)"
            ],
            "formatString": "0.00000",
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "Årsverk skolehelsetjenesten per 1 000 elever barnetrinn",
            "expression": [
              "",
              "",
              "var aarsverk = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"ÅRHOS\"),",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Årsverk barnetrinn totalt uten ledelse. Skolehelse barnetrinn\")",
              ")",
              "",
              "var elev = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12222\"), ",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] in {\"Elever i kommunale og private grunnskoler (antall) 1.-4. trinn\", \"Elever i kommunale og private grunnskoler (antall) 5.-7. trinn\"})",
              ")",
              "",
              "return DIVIDE(aarsverk,(elev/1000))",
              ""
            ],
            "formatString": "0.0",
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "Årsverk skolehelsetjenesten per 1 000 elever ungdomstrinn",
            "expression": [
              "",
              "",
              "var aarsverk = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"ÅRHOS\"),",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Årsverk ungdomstrinn totalt uten ledelse. Skolehelse ungdomstrinn\")",
              ")",
              "",
              "var elev = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12222\"), ",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Elever i kommunale og private grunnskoler (antall) 8.-10. trinn\")",
              ")",
              "",
              "return DIVIDE(aarsverk,(elev/1000))",
              "",
              ""
            ],
            "formatString": "0.0",
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "Årsverk skolehelse per innbygger 16-20 år VGS",
            "expression": [
              "",
              "",
              "var aarsverk = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"ÅRHOS\"),",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Årsverk vg skole totalt uten ledelse. Skolehelse videregående skole\")",
              ")",
              "",
              "var elev = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11805\"), ",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] in {\"Personer (antall) 16 år\", \"Personer (antall) 17 år\", \"Personer (antall) 18 år\", \"Personer (antall) 19 år\", \"Personer (antall) 20 år\"})",
              ")",
              "",
              "return divide(aarsverk,elev)",
              "",
              ""
            ],
            "formatString": "0.00000",
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "Årsverk kommunale fysioterapeuter i alt per 10 000 innbyggere",
            "expression": [
              "",
              "",
              "var aarsverk = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11995\"),",
              "FILTER(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] = \"FGK10\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Avtalte fysioterapeutårsverk (årsverk) Avtaleform i alt\")",
              ")",
              "var aarsverk241 = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11995\"),",
              "FILTER(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] = \"241\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Avtalte fysioterapeutårsverk (årsverk) Avtaleform i alt\")",
              ")",
              "",
              "var aarsverkfast = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11995\"),",
              "FILTER(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] = \"241\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Avtalte fysioterapeutårsverk (årsverk) Fastlønnet\")",
              ")",
              "",
              "var aarsverkturnus = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11995\"),",
              "FILTER(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] = \"241\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Avtalte fysioterapeutårsverk (årsverk) Turnusfysioterapeut\")",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11805\"),",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) I alt\")",
              ")",
              "",
              "return divide(((aarsverk-aarsverk241)+aarsverkfast+aarsverkturnus),(bef/10000))"
            ],
            "formatString": "0.0",
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "Årsverk private fysioterapeuter i alt per 10 000 innbyggere",
            "expression": [
              "",
              "",
              "var aarsverk = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11995\"),",
              "FILTER(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] = \"FGK10\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Avtalte fysioterapeutårsverk (årsverk) Tilskudd\")",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11805\"),",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) I alt\")",
              ")",
              "",
              "return divide(aarsverk,(bef/10000))",
              "",
              "",
              ""
            ],
            "formatString": "0.0",
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "Netto driftsutgifter per barn (f252) som er plassert av barnevernet (kroner)",
            "expression": [
              "",
              "",
              "var brbv = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "FILTER(ALL('Artsgruppe Kostra'[Artsgruppekode]),'Artsgruppe Kostra'[Artsgruppekode] = \"AGD2\"),",
              "FILTER(ALL('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] = \"252\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              " )",
              "",
              "return divide((brbv*1000),",
              "'Nøkkeltall tjenester'[Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)])"
            ],
            "formatString": "#,0",
            "displayFolder": "Barnevern"
          },
          {
            "name": "Andel av netto driftsutgifter barnevern f244 (prosent)",
            "expression": [
              "",
              "",
              "var nettobv = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "FILTER(ALL('Artsgruppe Kostra'[Artsgruppekode]),'Artsgruppe Kostra'[Artsgruppekode] = \"AGD2\"),",
              "FILTER(ALL('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] = \"FGK13\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var netto244 = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "FILTER(ALL('Artsgruppe Kostra'[Artsgruppekode]),'Artsgruppe Kostra'[Artsgruppekode] = \"AGD2\"),",
              "FILTER(ALL('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] = \"244\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "return (divide(netto244,nettobv))*100",
              ""
            ],
            "formatString": "0.0",
            "displayFolder": "Barnevern"
          },
          {
            "name": "Andel av netto driftsutgifter barnevern f251 (prosent)",
            "expression": [
              "",
              "",
              "var nettobv = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "FILTER(ALL('Artsgruppe Kostra'[Artsgruppekode]),'Artsgruppe Kostra'[Artsgruppekode] = \"AGD2\"),",
              "FILTER(ALL('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] = \"FGK13\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var netto251 = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "FILTER(ALL('Artsgruppe Kostra'[Artsgruppekode]),'Artsgruppe Kostra'[Artsgruppekode] = \"AGD2\"),",
              "FILTER(ALL('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] = \"251\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "return (divide(netto251,nettobv))*100",
              ""
            ],
            "formatString": "0.0",
            "displayFolder": "Barnevern"
          },
          {
            "name": "Andel av netto driftsutgifter barnevern f252 (prosent)",
            "expression": [
              "",
              "",
              "var nettobv = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "FILTER(ALL('Artsgruppe Kostra'[Artsgruppekode]),'Artsgruppe Kostra'[Artsgruppekode] = \"AGD2\"),",
              "FILTER(ALL('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] = \"FGK13\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var netto252 = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "FILTER(ALL('Artsgruppe Kostra'[Artsgruppekode]),'Artsgruppe Kostra'[Artsgruppekode] = \"AGD2\"),",
              "FILTER(ALL('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] = \"252\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "return (divide(netto252,nettobv))*100",
              ""
            ],
            "formatString": "0.0",
            "displayFolder": "Barnevern"
          },
          {
            "name": "Andel barn med melding av innbyggere 0-17 år (prosent)",
            "expression": [
              "",
              "",
              "var melding = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12615\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Barn med melding (antall)\")",
              ")",
              "",
              "var barn= CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(ALL('Alle Data'[Tabell]),'Alle Data'[Tabell]=\"11805\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) 0-17 år\")",
              ")",
              "",
              "return (divide(melding,barn))*100",
              ""
            ],
            "formatString": "#,0.0",
            "displayFolder": "Barnevern"
          },
          {
            "name": "Antall barn med undersøkelse eller tiltak per årsverk (funksjon 244)*",
            "expression": [
              "",
              "",
              "var barn = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12280\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Barn med undersøking eller tiltak per årsverk (funksjon 244) (antall)\")",
              ")",
              "",
              "return barn"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Barnevern"
          },
          {
            "name": "Korrigerte brutto driftsutgifter til kommunal eiendomsforvaltning per kvadratmeter (kroner)",
            "expression": [
              "",
              "",
              "var korrbreien = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "filter(all('Alle Data'[Artsgruppekode]), 'Alle Data'[Artsgruppekode]=\"AGD4\"),",
              "filter(all('Alle Data'[Funksjonskode]), 'Alle Data'[Funksjonskode] = \"FGK6a\"),",
              "FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var areal = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11906\"),",
              "filter(all('Alle Data'[Funksjonskode]), 'Alle Data'[Funksjonskode] = \"FGK6\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Areal (m2) Areal totalt\")",
              ")",
              "",
              "return divide((korrbreien*1000),areal)",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Eiendomsforvaltning"
          },
          {
            "name": "Korrigerte brutto driftsutgifter eksklusiv avskrivninger per kvadratmeter eiet bygg (kroner)",
            "expression": [
              "",
              "",
              "var brutto = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12559\"),",
              "filter(all('Alle Data'[Artsgruppekode]), 'Alle Data'[Artsgruppekode]=\"AGD4\"),",
              "filter(all('Alle Data'[Funksjonskode]), 'Alle Data'[Funksjonskode] = \"FGK6a\"),",
              "FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var avskr = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12559\"),",
              "filter(all('Alle Data'[Artsgruppekode]), 'Alle Data'[Artsgruppekode]=\"A590\"),",
              "filter(all('Alle Data'[Funksjonskode]), 'Alle Data'[Funksjonskode] = \"FGK6a\"),",
              "FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var leie = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12559\"),",
              "filter(all('Alle Data'[Artsgruppekode]), 'Alle Data'[Artsgruppekode]=\"A190\"),",
              "filter(all('Alle Data'[Funksjonskode]), 'Alle Data'[Funksjonskode] = \"FGK6a\"),",
              "FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var areal = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11906\"),",
              "filter(all('Alle Data'[Funksjonskode]), 'Alle Data'[Funksjonskode] = \"FGK6\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Areal (m2) Eid areal\")",
              ")",
              "",
              "return divide((brutto-(leie+avskr)),areal)*1000",
              "",
              "",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Eiendomsforvaltning"
          },
          {
            "name": "Utgifter til renholdsaktiviteter i kommunal eiendomsforvaltning, per kvadratmeter (kroner)",
            "expression": [
              "",
              "",
              "var renhold = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12047\"),",
              "filter(all('Alle Data'[Artsgruppekode]), 'Alle Data'[Artsgruppekode]=\"AGD38\"),",
              "filter(all('Alle Data'[Funksjonskode]), 'Alle Data'[Funksjonskode] = \"FGK6\"),",
              "FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var areal = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11906\"),",
              "filter(all('Alle Data'[Funksjonskode]), 'Alle Data'[Funksjonskode] = \"FGK6\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Areal (m2) Eid areal\")",
              ")",
              "",
              "return divide((renhold*1000),areal)",
              "",
              "",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Eiendomsforvaltning"
          },
          {
            "name": "Korrigert brutto driftsutgifter til kommunal forvaltning av eiendommer per kvadratmeter (kroner)",
            "expression": [
              "",
              "",
              "var korrbreien = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "filter(all('Alle Data'[Artsgruppekode]), 'Alle Data'[Artsgruppekode]=\"AGD4\"),",
              "filter(all('Alle Data'[Funksjonskode]), 'Alle Data'[Funksjonskode] = \"121\"),",
              "FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var areal = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11906\"),",
              "filter(all('Alle Data'[Funksjonskode]), 'Alle Data'[Funksjonskode] = \"FGK6\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Areal (m2) Areal totalt\")",
              ")",
              "",
              "return divide((korrbreien*1000),areal)",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Eiendomsforvaltning"
          },
          {
            "name": "Utgifter til driftsaktiviteter i kommunal eiendomsforvaltning, per kvadratmeter (kroner)",
            "expression": [
              "",
              "",
              "var drift = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12047\"),",
              "filter(all('Alle Data'[Artsgruppekode]), 'Alle Data'[Artsgruppekode]=\"AGD39\"),",
              "filter(all('Alle Data'[Funksjonskode]), 'Alle Data'[Funksjonskode] = \"FGK6\"),",
              "FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var areal = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11906\"),",
              "filter(all('Alle Data'[Funksjonskode]), 'Alle Data'[Funksjonskode] = \"FGK6\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Areal (m2) Eid areal\")",
              ")",
              "",
              "return divide((drift*1000),areal)",
              "",
              "",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Eiendomsforvaltning"
          },
          {
            "name": "Utgifter til vedlikeholdsaktiviteter i kommunal eiendomsforvaltning, per kvadratmeter (kroner)",
            "expression": [
              "",
              "",
              "var ved = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12047\"),",
              "filter(all('Alle Data'[Artsgruppekode]), 'Alle Data'[Artsgruppekode]=\"AGD36\"),",
              "filter(all('Alle Data'[Funksjonskode]), 'Alle Data'[Funksjonskode] = \"FGK6\"),",
              "FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var areal = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11906\"),",
              "filter(all('Alle Data'[Funksjonskode]), 'Alle Data'[Funksjonskode] = \"FGK6\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Areal (m2) Eid areal\")",
              ")",
              "",
              "return divide((ved*1000),areal)",
              "",
              "",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Eiendomsforvaltning"
          },
          {
            "name": "Sykefravær eiendomsforvaltning (PAI) (prosent)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"ASSS\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Sykefravær Eiendomsforvaltning i Alt (PAI)\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "0.0",
            "displayFolder": "Eiendomsforvaltning"
          },
          {
            "name": "Innbyggertall pensjon barnehage_ny",
            "expression": [
              "If(Calculate(Sum('Alle Data'[Verdi]), ",
              "'Variabel'[Variabelnavn] = \"Beløp (1000 kr)\", ",
              "'Kommune'[Kostrakategori] =\"Kommune\",",
              "'Artsgruppe Kostra'[Artsgruppekode]=\"AG16\",'Alle Data'[Funksjonskode] IN {\"201\", \"211\", \"221\"}) < 100, 0,[Innbyggere 1. juli])"
            ],
            "formatString": "#,0",
            "displayFolder": "Økonomi"
          },
          {
            "name": "Stillinger med fagutdanning av alle fag- og tiltaksstillinger (prosent)",
            "expression": [
              "",
              "",
              "var fag = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12305\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Stillingar med fagutdanning (årsverk)\")",
              ")",
              "",
              "var stillinger= CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(ALL('Alle Data'[Tabell]),'Alle Data'[Tabell]=\"12305\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = ",
              "\"Stillingar knytt til sakshandsaming og tiltak frå barnevernstenesta (funksjon 244 unnateke støttefunksjonar, funksjon 251 og 252)  (årsverk)\")",
              ")",
              "",
              "return (divide(fag,stillinger)*100)",
              ""
            ],
            "formatString": "#,0.0",
            "displayFolder": "Barnevern"
          },
          {
            "name": "Andel meldinger som går til undersøkelser (prosent)",
            "expression": [
              "",
              "",
              "var und = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12189\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = ",
              "\"Meldingar til barnevernet (antall) Til undersøkelse Meldinger i alt\")",
              ")",
              "",
              "var meld= CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(ALL('Alle Data'[Tabell]),'Alle Data'[Tabell]=\"12189\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = ",
              "\"Meldingar til barnevernet (antall) Meldinger i alt Meldinger i alt\")",
              ")",
              "",
              "return (divide(und,meld)*100)",
              ""
            ],
            "formatString": "#,0.0",
            "displayFolder": "Barnevern"
          },
          {
            "name": "Sykefravær byggesak (PAI) (prosent)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"ASSS\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Sykefravær Byggesak (PAI)\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "0.0",
            "displayFolder": "Byggesak"
          },
          {
            "name": "Brutto driftsutgifter per EM (f252) (kroner)",
            "expression": [
              "",
              "",
              "var brem = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"BMT\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=",
              "\"Brutto driftsutgifter funksjon 252 enslige mindreårige (1000 kr)\")",
              ")",
              "var antall = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"BMT\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=",
              "\"Antall enslige mindreårige f252\")",
              ")",
              "return divide((brem*1000),antall)"
            ],
            "formatString": "#,0",
            "displayFolder": "Barnevern"
          },
          {
            "name": "Brutto driftsutgifter per plassert barn uten EM (f252) (kroner)",
            "expression": [
              "",
              "",
              "var brbv = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "FILTER(ALL('Artsgruppe Kostra'[Artsgruppekode]),'Artsgruppe Kostra'[Artsgruppekode] = \"AGD10\"),",
              "FILTER(ALL('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] = \"252\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var brem = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"BMT\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=",
              "\"Brutto driftsutgifter funksjon 252 enslige mindreårige (1000 kr)\")",
              ")",
              "var antall = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"BMT\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=",
              "\"Antall enslige mindreårige f252\")",
              ")",
              "",
              "return DIVIDE(((brbv-brem)*1000),",
              "('Nøkkeltall tjenester'[Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)]-antall))"
            ],
            "formatString": "#,0",
            "displayFolder": "Barnevern"
          },
          {
            "name": "Andel EM av alle plasserte barn (prosent)",
            "expression": [
              "",
              "",
              "var antall = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"BMT\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=",
              "\"Antall enslige mindreårige f252\")",
              ")",
              "",
              "return (DIVIDE(antall,('Nøkkeltall tjenester'[Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)]))*100)"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Barnevern"
          },
          {
            "name": "Andel barn med tiltak 0-5 år av barn på tiltak 0-17 år (prosent)",
            "expression": [
              "",
              "",
              "var antall1 = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"BMT\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=",
              "\"Barn med barnevernstiltak i løpet av året, etter aldersgrupper - 0-5 år\")",
              ")",
              "var antall2 = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"BMT\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] in ",
              "{\"Barn med barnevernstiltak i løpet av året, etter aldersgrupper - 0-5 år\",",
              "\"Barn med barnevernstiltak i løpet av året, etter aldersgrupper - 6-12 år\",",
              "\"Barn med barnevernstiltak i løpet av året, etter aldersgrupper - 13-17 år\"})",
              ")",
              "",
              "return (DIVIDE(antall1,antall2)*100)"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Barnevern"
          },
          {
            "name": "Godkjente boligenheter per 1 000 innbyggere",
            "expression": [
              "",
              "",
              "var var1 = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"05940\"), ",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Fullførte boliger\") ",
              ") ",
              "var var2 = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11805\"), ",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) I alt\") ",
              ")  ",
              "",
              "",
              "return divide(var1,(var2/1000))",
              ""
            ],
            "formatString": "#,0.0",
            "displayFolder": "Byggesak"
          },
          {
            "name": "Godkjent annet areal per 1 000 innbyggere",
            "expression": [
              "",
              "",
              "var var1 = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"05939\"), ",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Fullført bruksareal til annet enn bolig\") ",
              ") ",
              "var var2 = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11805\"), ",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) I alt\") ",
              ")  ",
              "",
              "",
              "return divide(var1,(var2/1000))"
            ],
            "formatString": "#,0",
            "displayFolder": "Byggesak"
          },
          {
            "name": "Gjennomsnittlig saksbehandlingstid ett-trinnssøknader, 12-uker (dager)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12295\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Gjennomsnittlig saksbehandlingstid for byggesaker med 12 ukers frist (dager)\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "Byggesak"
          },
          {
            "name": "Saksbehandlingsgebyr for oppføring av enebolig (kroner)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12303\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Byggesaksgebyr for oppføring av enebolig (kr)\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "Byggesak"
          },
          {
            "name": "Nye søknader per 1 000 innbyggere",
            "expression": [
              "",
              "",
              "var var1 = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11211\"), ",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Antall søknader mottatt av kommunen\") ",
              ") ",
              "var var2 = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11805\"), ",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) I alt\") ",
              ")  ",
              "",
              "",
              "return divide(var1,(var2/1000))",
              ""
            ],
            "formatString": "#,0.0",
            "displayFolder": "Byggesak"
          },
          {
            "name": "Tilsyn i % av nye byggesaker",
            "expression": [
              "",
              "",
              "var var1 = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12224\"), ",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Byggesaker med tilsyn (antall)\") ",
              ")  ",
              "var var2 = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12224\"), ",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Behandlede byggesøknader i alt (antall)\") ",
              ") ",
              "",
              "return (divide(var1,var2))*100",
              ""
            ],
            "formatString": "#,0.0",
            "displayFolder": "Byggesak"
          },
          {
            "name": "Antall utførte tilsyn med ikke omsøkt byggevirksomhet*",
            "expression": [
              "",
              "",
              "var var1 = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11879\"), ",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Tilsyn i ikke omsøkte byggesaker (antall)\") ",
              ")  ",
              "",
              "return (var1)"
            ],
            "formatString": "#,0",
            "displayFolder": "Byggesak"
          },
          {
            "name": "Andel mangelfulle søknader i prosent av vedtak",
            "expression": [
              "",
              "",
              "var var1 = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11211\"), ",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Antall mangelfulle søknader hvor det ble bedt om tilleggsdokumentasjon\") ",
              ")  ",
              "var var2 = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11211\"), ",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Antall søknader kommunen behandlet ferdig (fattet vedtak om)\") ",
              ") ",
              "",
              "return (divide(var1,var2))*100",
              ""
            ],
            "formatString": "#,0.0",
            "displayFolder": "Byggesak"
          },
          {
            "name": "Brutto driftsutgifter per ferdigbehandlet byggesak (f302) (kroner)",
            "expression": [
              "",
              "",
              "var var1 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12611\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"302\"}),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"2. Brutto driftsutgifter (1000 kr)\")",
              ")",
              "var var2 = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11211\"), ",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Antall søknader kommunen behandlet ferdig (fattet vedtak om)\") ",
              ") ",
              "",
              "return ((divide(var1,var2))*1000)",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Byggesak"
          },
          {
            "name": "Andel vedtak innenfor frist (prosent)",
            "expression": [
              "",
              " ",
              "var var1 = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11211\"), ",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Antall søknader med saksbehandlingstid over lovpålagt tid\") ",
              ") ",
              "var var2 = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11211\"), ",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Antall søknader mottatt av kommunen\") ",
              ")",
              "",
              "return (divide((var2-var1),var2))*100",
              ""
            ],
            "formatString": "#,0.0",
            "displayFolder": "Byggesak"
          },
          {
            "name": "Totale gebyrinntekter bygge- og delesaksbehandling per f.g.vedtak (kroner)",
            "expression": [
              "",
              "",
              "var var1 = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12299\"), ",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Beløp (1000 kr) Bygge- og delesaksbehandling Gebyrinntekter\") ",
              ")  ",
              "var var2 = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11211\"), ",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Antall søknader kommunen behandlet ferdig (fattet vedtak om)\") ",
              ") ",
              "",
              "return (divide((var1*1000),var2))"
            ],
            "formatString": "#,0",
            "displayFolder": "Byggesak"
          },
          {
            "name": "Samlet energibruk i kommunal eiendomsforvaltning kWh/m2*",
            "expression": [
              "",
              "",
              "var energi = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12150\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] = \"FGK6\"),",
              "FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Energibruk (MWh)\")",
              ")",
              "var areal = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11906\"),",
              "filter(all('Alle Data'[Funksjonskode]), 'Alle Data'[Funksjonskode] = \"FGK6\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Areal (m2) Eid areal\")",
              ")",
              "return DIVIDE((energi*1000),areal)",
              "",
              "",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Eiendomsforvaltning"
          },
          {
            "name": "Årsverk jordmor per 10 000 fødte",
            "expression": [
              "",
              "",
              "var var1 = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11994\"),",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Avtalte årsverk (årsverk) Jordmor\")",
              ")",
              "",
              "var var2= CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11820\"),",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Fødte i løpet av året (antall)\")",
              ")",
              "",
              "return (divide(var1,(var2/10000)))"
            ],
            "formatString": "0.0",
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "Årsverk leger per 10 000 innbyggere 0-5 år",
            "expression": [
              "",
              "",
              "var var1 = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11994\"),",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Avtalte årsverk (årsverk) Leger\")",
              ")",
              "",
              "var var2= CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11805\"),",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) 0-5 år\")",
              ")",
              "",
              "return (divide(var1,(var2/10000)))"
            ],
            "formatString": "0.0",
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "Spedbarnundersøkelse 8. leveuke (prosent)",
            "expression": [
              "",
              "",
              "var und = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11993\"),",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Barn (antall) Undersøkt 8. leveuke\")",
              ")",
              "",
              "var barn= CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11820\"),",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Fødte i løpet av året (antall)\")",
              ")",
              "",
              "return divide(und,barn)*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "Helseundersøkelse 2-3 år (prosent)",
            "expression": [
              "",
              "",
              "var und = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11993\"),",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Barn (antall) Undersøkt ved 2-års alder\")",
              ")",
              "",
              "var barn= CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11805\"),",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) 2-3 år\")",
              ")",
              "",
              "return divide(und,(barn/2))*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "Helseundersøkelse 4 år (prosent)",
            "expression": [
              "",
              "",
              "var und = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11993\"),",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Barn (antall) Undersøkt ved 4-års alder\")",
              ")",
              "",
              "var barn= CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11805\"),",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) 4 år\")",
              ")",
              "",
              "return divide(und,barn)*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "Helseundersøkelse 1. trinn (prosent)",
            "expression": [
              "",
              "",
              "var und = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11993\"),",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Barn (antall) Undersøkt grunnskole 1. trinn\")",
              ")",
              "",
              "var barn= CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11805\"),",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) 5-6 år\")",
              ")",
              "",
              "return divide(und,(barn/2))*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "Copy of Innbyggertall pensjon barnehage",
            "expression": [
              "If(Calculate(Sum('Alle Data'[Verdi]), ",
              "'Variabel'[Variabelnavn] = \"Beløp (1000 kr)\", ",
              "'Kommune'[Kostrakategori] in {\"Kommune\", \"Landet\"},",
              "'År'[År] in {2017, 2016, 2015},",
              "'Artsgruppe Kostra'[Artsgruppekode]=\"AG16\",'Alle Data'[Funksjonskode] IN {\"201\", \"211\", \"221\"}) < 100, 0,[Innbyggere 1. juli])"
            ],
            "formatString": "#,0",
            "displayFolder": "Økonomi"
          },
          {
            "name": "Test1234",
            "expression": [
              "",
              "",
              "CALCULATE([Test12345], ALLSELECTED(Kommune), 'År')"
            ],
            "formatString": "#,0",
            "displayFolder": "Økonomi"
          },
          {
            "name": "Test12345",
            "expression": [
              "",
              "",
              "var var1 = CALCULATE(sum('Alle Data'[Verdi]), ",
              "FILTER(all('Nøkkeltall tjenester'[Andre]),[Innbyggertall pensjon barnehage_ny] > 0),",
              "FILTER(ALL('Kommune'[Kostrakategori]), Kommune[Kostrakategori]=\"Kommune\"),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"GHFK\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Innbyggertall per 1. juli (Kilde: Grønt Hefte)\"),",
              "FILTER(ALL('År'[År]), 'År'[År] in {2015, 2016, 2017})",
              "",
              ")",
              "return var1",
              ""
            ],
            "isHidden": true,
            "displayFolder": "Økonomi"
          },
          {
            "name": "Copy of Test1234",
            "expression": [
              "",
              "",
              "CALCULATE([Test12345], ALLSELECTED('År'[År]))"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Økonomi"
          },
          {
            "name": "Stønadslengde mottakere med sosialhjelp som hovedinntektskilde. Snitt måneder per år*",
            "expression": [
              "",
              "",
              "var lengde = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12213\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Gjennomsnittlig stønadslengde for mottakere med sosialhjelp som hovedinntekt  (måneder)\")",
              ")",
              "",
              "return lengde"
            ],
            "formatString": "0.0",
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "Ressursbruksindikator. Sosiale tjenester*",
            "expression": [
              "",
              "",
              "var r = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"RBIASSS\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Ressursbruksindikator Sosiale tjenester\")",
              ")",
              "",
              "return r"
            ],
            "formatString": "0.000",
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "Ressursbruksindikator. Kommunehelse*",
            "expression": [
              "",
              "",
              "var r = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"RBIASSS\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Ressursbruksindikator Kommunehelse\")",
              ")",
              "",
              "return r"
            ],
            "formatString": "0.000",
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "Ressursbruksindikator. Grunnskole*",
            "expression": [
              "",
              "",
              "var r = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"RBIASSS\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Ressursbruksindikator Grunnskole\")",
              ")",
              "",
              "return r"
            ],
            "formatString": "0.000",
            "displayFolder": "Grunnskole"
          },
          {
            "name": "Ressursbruksindikator. Grunnskole F202*",
            "expression": [
              "",
              "",
              "var r = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"RBIASSS\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Ressursbruksindikator Grunnskole F202\")",
              ")",
              "",
              "return r"
            ],
            "formatString": "0.000",
            "displayFolder": "Grunnskole"
          },
          {
            "name": "Ressursbruksindikator. Barnevern*",
            "expression": [
              "",
              "",
              "var r = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"RBIASSS\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Ressursbruksindikator Barnevern\")",
              ")",
              "",
              "return r"
            ],
            "formatString": "0.000",
            "displayFolder": "Barnevern"
          },
          {
            "name": "Ressursbruksindikator. Barnehager*",
            "expression": [
              "",
              "",
              "var r = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"RBIASSS\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Ressursbruksindikator Barnehager\")",
              ")",
              "",
              "return r"
            ],
            "formatString": "0.000",
            "displayFolder": "Barnehager"
          },
          {
            "name": "Ressursbruksindikator. Pleie og omsorg*",
            "expression": [
              "",
              "",
              "var r = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"RBIASSS\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Ressursbruksindikator Pleie og omsorg\")",
              ")",
              "",
              "return r"
            ],
            "formatString": "0.000",
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "Brutto investeringsutgifter til kommunale veier og gater per innbygger (kroner)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11816\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Brutto investeringsutgifter til kommunale veier og gater per innbygger (kr)\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "Samferdsel"
          },
          {
            "name": "Sykefravær pleie og omsorg (PAI) (prosent)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"ASSS\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Sykefravær Pleie og omsorg (PAI)\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "0.0",
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "Legetimer per uke per beboer i sykehjem (timer)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12293\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Legetimer per uke per beboer i sykehjem (timer)\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "0.00",
            "displayFolder": "Pleie og omsorg"
          }
        ]
      },
      {
        "name": "Regnskap",
        "columns": [
          {
            "name": "Generelle",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Generelle"
          },
          {
            "name": "Beregninger",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Beregninger"
          },
          {
            "name": "Annet",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Annet"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/SQL2018\\TAB;Reporting\",",
                "    dbo_Regnskap = Source{[Schema=\"dbo\",Item=\"Regnskap\"]}[Data]",
                "in",
                "    dbo_Regnskap"
              ]
            }
          }
        ]
      },
      {
        "name": "Produksjonsindeks",
        "columns": [
          {
            "name": "Generelle",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Generelle"
          },
          {
            "name": "Beregninger",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Beregninger"
          },
          {
            "name": "Annet",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Annet"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/SQL2018\\TAB;Reporting\",",
                "    dbo_Produksjonsindeks = Source{[Schema=\"dbo\",Item=\"Produksjonsindeks\"]}[Data]",
                "in",
                "    dbo_Produksjonsindeks"
              ]
            }
          }
        ]
      },
      {
        "name": "Tabeller",
        "columns": [
          {
            "name": "Tabellnummer",
            "dataType": "string",
            "sourceColumn": "Tabellnummer"
          },
          {
            "name": "Tabellnavn",
            "dataType": "string",
            "sourceColumn": "Tabellnavn"
          },
          {
            "name": "TabellNummerNavn",
            "dataType": "string",
            "sourceColumn": "TabellNummerNavn"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/SQL2018\\TAB;Reporting\",",
                "    dbo_Tabeller = Source{[Schema=\"dbo\",Item=\"Tabeller\"]}[Data]",
                "in",
                "    dbo_Tabeller"
              ]
            }
          }
        ]
      },
      {
        "name": "Effektivitet",
        "columns": [
          {
            "name": "Generelle",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Generelle"
          },
          {
            "name": "Beregninger",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Beregninger"
          },
          {
            "name": "Annet",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Annet"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/SQL2018\\TAB;Reporting\",",
                "    dbo_Effektivitet = Source{[Schema=\"dbo\",Item=\"Effektivitet\"]}[Data]",
                "in",
                "    dbo_Effektivitet"
              ]
            }
          }
        ]
      },
      {
        "name": "Ressursbruksindikator",
        "columns": [
          {
            "name": "RBBarnehage",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "RBBarnehage"
          },
          {
            "name": "RBKommunehelse",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "RBKommunehelse"
          },
          {
            "name": "RBPleieOgOmsorg",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "RBPleieOgOmsorg"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/SQL2018\\TAB;Reporting\",",
                "    dbo_Ressursbruksindikator = Source{[Schema=\"dbo\",Item=\"Ressursbruksindikator\"]}[Data]",
                "in",
                "    dbo_Ressursbruksindikator"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "1 Netto driftsutgifter barnehage (kroner)",
            "expression": [
              "",
              "",
              "var nettobhg = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer]=\"12367\"),",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]), 'Artsgruppe Kostra'[Artsgruppekode]=\"AGD2\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"201\", \"211\", \"221\"}),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "",
              "return (nettobhg)"
            ],
            "displayFolder": "Utregninger"
          },
          {
            "name": "Innbyggere 1.7.",
            "expression": [
              "",
              "",
              "var innb = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] =\"Innbyggertall per 1. juli\")",
              ")",
              "return (innb)",
              "",
              ""
            ],
            "displayFolder": "Utregninger"
          },
          {
            "name": "Netto drift eks avskrivning pr innb",
            "expression": [
              "",
              "",
              "([1 Netto driftsutgifter barnehage (kroner)]-[Avskrivninger barnehage (kroner)])/[Innbyggere 1.7.]*1000"
            ],
            "displayFolder": "Utregninger"
          },
          {
            "name": "Avskrivninger barnehage (kroner)",
            "expression": [
              "",
              "",
              "var avsbhg = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer]=\"12367\"),",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]), 'Artsgruppe Kostra'[Artsgruppekode]=\"A590\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"201\", \"211\", \"221\"}),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "",
              "return (avsbhg)"
            ],
            "displayFolder": "Utregninger"
          },
          {
            "name": "Beregnet UB",
            "expression": [
              "",
              "",
              "var I2_5aar = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] =\"Indeks innb. 2-5 år\")",
              ")",
              "",
              "",
              "var Iukont = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] =\"Indeks barn 1 år utan kontant-støtte\")",
              ")",
              "",
              "var IndHoyUtd  = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] =\"Indeks innb. m. høgare ut-danning\")",
              ")",
              "",
              "/* OBS hardkodede vekter - må lage en fil for dette */",
              "return (I2_5aar*0.78160)+(Iukont*0.10420)+(IndHoyUtd*0.11420)"
            ],
            "displayFolder": "Utregninger"
          },
          {
            "name": "TesterMF",
            "expression": [
              " ",
              "",
              "/*var vekttest2 = Calculate(sum('Alle Data'[Verdi]);*/",
              "/*FIRSTNONBLANK(Variabel[Variabelnavn]; Variabel[Variabelnavn] = \"Innb 2-5 år vektinger\"))*/",
              "",
              "/*return (vekttest2)*/",
              "",
              "VAR vekttest2 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Innb 2-5 år vektinger\"),",
              "filter(all('Kommune'[Kommunenummer]),'Kommune'[Kommunenummer] = \"EAK\")",
              ")",
              "",
              "var vekt2 = ",
              "CALCULATE(",
              "  SUM('Alle Data'[Verdi]),",
              "  FILTER(ALL(Variabel[Variabelnavn]),Variabel[Variabelnavn] = \"Innb 2-5 år vektinger\")",
              "",
              "  /*FILTER(ALL('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] IN {\"201\"; \"211\"; \"221\"});*/",
              "  /*FILTER(ALL('Kommune'[Kommunenummer]);'Kommune'[Kommunenummer] = \"EAK\")*/",
              ") ",
              "",
              "",
              "",
              "RETURN vekt2",
              ""
            ],
            "displayFolder": "Utregninger"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "a1e3098f-0ae2-497a-b449-a3c29f1783fd",
        "fromTable": "Kommune",
        "fromColumn": "Regionnummer",
        "toTable": "Region",
        "toColumn": "Regionnummer"
      },
      {
        "name": "1664319a-338c-456b-95a6-0b8863cc46d9",
        "fromTable": "Alle Data",
        "fromColumn": "Funksjonskode",
        "toTable": "Funksjon Kostra",
        "toColumn": "Funksjonskode"
      },
      {
        "name": "d811264d-a1e9-4923-a94b-580548240bcf",
        "fromTable": "Alle Data",
        "fromColumn": "Variabel",
        "toTable": "Variabel",
        "toColumn": "Variabel"
      },
      {
        "name": "bcc6acb4-14db-4ebc-8c02-728a407c982e",
        "fromTable": "Alle Data",
        "fromColumn": "År",
        "toTable": "År",
        "toColumn": "År"
      },
      {
        "name": "f7ca8293-7539-4f58-82ba-a88474e80a5e",
        "fromTable": "Alle Data",
        "fromColumn": "Kommunenummer",
        "toTable": "Kommune",
        "toColumn": "Kommunenummer"
      },
      {
        "name": "6b78c631-613c-4209-97da-d1f30fc340c4",
        "fromTable": "Alle Data",
        "fromColumn": "Artsgruppekode",
        "toTable": "Artsgruppe Kostra",
        "toColumn": "Artsgruppekode"
      },
      {
        "name": "45c41c6c-7006-483e-ac3d-d3d9cb61c192",
        "fromTable": "Alle Data",
        "fromColumn": "Tabell",
        "toTable": "Tabeller",
        "toColumn": "Tabellnummer"
      }
    ],
    "roles": [
      {
        "name": "Role",
        "modelPermission": "administrator",
        "members": [
          {
            "memberName": "S-1-5-80-4112458140-3731046597-1830558082-4050242181-648104384",
            "memberId": "S-1-5-80-4112458140-3731046597-1830558082-4050242181-648104384"
          },
          {
            "memberName": "S-1-5-21-3724942605-3563258533-3430695148-1049",
            "memberId": "S-1-5-21-3724942605-3563258533-3430695148-1049"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "500"
      }
    ]
  },
  "id": "SemanticModel"
}